// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package arohcpapi

type ACR struct {
	// Resource names may contain alpha numeric characters only and must be between 5
	// and 50 characters. We limited the length to 44 characters so we have a future
	// option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

type AKSAgentPool struct {
	// AZCount corresponds to the JSON schema field "azCount".
	AZCount *float64 `json:"azCount,omitempty" yaml:"azCount,omitempty" mapstructure:"azCount,omitempty"`

	// MaxCount corresponds to the JSON schema field "maxCount".
	MaxCount float64 `json:"maxCount" yaml:"maxCount" mapstructure:"maxCount"`

	// MinCount corresponds to the JSON schema field "minCount".
	MinCount float64 `json:"minCount" yaml:"minCount" mapstructure:"minCount"`

	// OsDiskSizeGB corresponds to the JSON schema field "osDiskSizeGB".
	OsDiskSizeGB float64 `json:"osDiskSizeGB" yaml:"osDiskSizeGB" mapstructure:"osDiskSizeGB"`

	// VmSize corresponds to the JSON schema field "vmSize".
	VmSize string `json:"vmSize" yaml:"vmSize" mapstructure:"vmSize"`
}

type AKSConfig struct {
	// ClusterOutboundIPAddressIPTags corresponds to the JSON schema field
	// "clusterOutboundIPAddressIPTags".
	ClusterOutboundIPAddressIPTags KeyColonValueCSV `json:"clusterOutboundIPAddressIPTags" yaml:"clusterOutboundIPAddressIPTags" mapstructure:"clusterOutboundIPAddressIPTags"`

	// EnableSwiftV2Nodepools corresponds to the JSON schema field
	// "enableSwiftV2Nodepools".
	EnableSwiftV2Nodepools *bool `json:"enableSwiftV2Nodepools,omitempty" yaml:"enableSwiftV2Nodepools,omitempty" mapstructure:"enableSwiftV2Nodepools,omitempty"`

	// EnableSwiftV2Vnet corresponds to the JSON schema field "enableSwiftV2Vnet".
	EnableSwiftV2Vnet *bool `json:"enableSwiftV2Vnet,omitempty" yaml:"enableSwiftV2Vnet,omitempty" mapstructure:"enableSwiftV2Vnet,omitempty"`

	// Etcd corresponds to the JSON schema field "etcd".
	Etcd AKSConfigEtcd `json:"etcd" yaml:"etcd" mapstructure:"etcd"`

	// InfraAgentPool corresponds to the JSON schema field "infraAgentPool".
	InfraAgentPool *AKSAgentPool `json:"infraAgentPool,omitempty" yaml:"infraAgentPool,omitempty" mapstructure:"infraAgentPool,omitempty"`

	// KubernetesVersion corresponds to the JSON schema field "kubernetesVersion".
	KubernetesVersion string `json:"kubernetesVersion" yaml:"kubernetesVersion" mapstructure:"kubernetesVersion"`

	// The name needs to be between 3-63 characters and can contain only letters,
	// numbers, underscores, and hyphens. The name must start and end with a letter or
	// number. We limit the name to 44 characters so we have a future option to use
	// NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// NetworkDataplane corresponds to the JSON schema field "networkDataplane".
	NetworkDataplane AKSConfigNetworkDataplane `json:"networkDataplane" yaml:"networkDataplane" mapstructure:"networkDataplane"`

	// NetworkPolicy corresponds to the JSON schema field "networkPolicy".
	NetworkPolicy AKSConfigNetworkPolicy `json:"networkPolicy" yaml:"networkPolicy" mapstructure:"networkPolicy"`

	// PodSubnetPrefix corresponds to the JSON schema field "podSubnetPrefix".
	PodSubnetPrefix string `json:"podSubnetPrefix" yaml:"podSubnetPrefix" mapstructure:"podSubnetPrefix"`

	// SubnetPrefix corresponds to the JSON schema field "subnetPrefix".
	SubnetPrefix string `json:"subnetPrefix" yaml:"subnetPrefix" mapstructure:"subnetPrefix"`

	// SystemAgentPool corresponds to the JSON schema field "systemAgentPool".
	SystemAgentPool AKSAgentPool `json:"systemAgentPool" yaml:"systemAgentPool" mapstructure:"systemAgentPool"`

	// UserAgentPool corresponds to the JSON schema field "userAgentPool".
	UserAgentPool AKSAgentPool `json:"userAgentPool" yaml:"userAgentPool" mapstructure:"userAgentPool"`

	// VnetAddressPrefix corresponds to the JSON schema field "vnetAddressPrefix".
	VnetAddressPrefix string `json:"vnetAddressPrefix" yaml:"vnetAddressPrefix" mapstructure:"vnetAddressPrefix"`
}

type AKSConfigEtcd struct {
	// KVName corresponds to the JSON schema field "kvName".
	KVName KeyVaultName `json:"kvName" yaml:"kvName" mapstructure:"kvName"`

	// KVSoftDelete corresponds to the JSON schema field "kvSoftDelete".
	KVSoftDelete bool `json:"kvSoftDelete" yaml:"kvSoftDelete" mapstructure:"kvSoftDelete"`
}

type AKSConfigNetworkDataplane string

const AKSConfigNetworkDataplaneAzure AKSConfigNetworkDataplane = "azure"
const AKSConfigNetworkDataplaneCilium AKSConfigNetworkDataplane = "cilium"
type AKSConfigNetworkPolicy string

const AKSConfigNetworkPolicyAzure AKSConfigNetworkPolicy = "azure"
const AKSConfigNetworkPolicyCilium AKSConfigNetworkPolicy = "cilium"
type AKSLogConfig struct {
	// Geneva logs account namespace configuration version
	ConfigVersion string `json:"configVersion" yaml:"configVersion" mapstructure:"configVersion"`

	// Geneva logs account namespace
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// Geneva logs account certificate SAN
	SAN string `json:"san" yaml:"san" mapstructure:"san"`
}

type Audit struct {
	// TcpAddress corresponds to the JSON schema field "tcpAddress".
	TcpAddress string `json:"tcpAddress" yaml:"tcpAddress" mapstructure:"tcpAddress"`
}

type CertificateIssuer string

const CertificateIssuerOneCertV2PrivateCA CertificateIssuer = "OneCertV2-PrivateCA"
const CertificateIssuerOneCertV2PublicCA CertificateIssuer = "OneCertV2-PublicCA"
const CertificateIssuerSelf CertificateIssuer = "Self"
type CertificateRef struct {
	// KeyVault corresponds to the JSON schema field "keyVault".
	KeyVault KeyVaultName `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ConfigSchemaJSON struct {
	// Acm corresponds to the JSON schema field "acm".
	Acm *ConfigSchemaJSONAcm `json:"acm,omitempty" yaml:"acm,omitempty" mapstructure:"acm,omitempty"`

	// ACR corresponds to the JSON schema field "acr".
	ACR *ConfigSchemaJSONACR `json:"acr,omitempty" yaml:"acr,omitempty" mapstructure:"acr,omitempty"`

	// ACRPull corresponds to the JSON schema field "acrPull".
	ACRPull ConfigSchemaJSONACRPull `json:"acrPull" yaml:"acrPull" mapstructure:"acrPull"`

	// Administration corresponds to the JSON schema field "administration".
	Administration ConfigSchemaJSONAdministration `json:"administration" yaml:"administration" mapstructure:"administration"`

	// ARMHelperCertName corresponds to the JSON schema field "armHelperCertName".
	ARMHelperCertName *string `json:"armHelperCertName,omitempty" yaml:"armHelperCertName,omitempty" mapstructure:"armHelperCertName,omitempty"`

	// ARMHelperClientId corresponds to the JSON schema field "armHelperClientId".
	ARMHelperClientId *string `json:"armHelperClientId,omitempty" yaml:"armHelperClientId,omitempty" mapstructure:"armHelperClientId,omitempty"`

	// ARMHelperFPAPrincipalId corresponds to the JSON schema field
	// "armHelperFPAPrincipalId".
	ARMHelperFPAPrincipalId *string `json:"armHelperFPAPrincipalId,omitempty" yaml:"armHelperFPAPrincipalId,omitempty" mapstructure:"armHelperFPAPrincipalId,omitempty"`

	// Arobit corresponds to the JSON schema field "arobit".
	Arobit *ConfigSchemaJSONArobit `json:"arobit,omitempty" yaml:"arobit,omitempty" mapstructure:"arobit,omitempty"`

	// Backend corresponds to the JSON schema field "backend".
	Backend *ConfigSchemaJSONBackend `json:"backend,omitempty" yaml:"backend,omitempty" mapstructure:"backend,omitempty"`

	// BackplaneAPI corresponds to the JSON schema field "backplaneAPI".
	BackplaneAPI ConfigSchemaJSONBackplaneAPI `json:"backplaneAPI" yaml:"backplaneAPI" mapstructure:"backplaneAPI"`

	// Cloud corresponds to the JSON schema field "cloud".
	Cloud *string `json:"cloud,omitempty" yaml:"cloud,omitempty" mapstructure:"cloud,omitempty"`

	// ClustersService corresponds to the JSON schema field "clustersService".
	ClustersService ConfigSchemaJSONClustersService `json:"clustersService" yaml:"clustersService" mapstructure:"clustersService"`

	// CxKeyVault corresponds to the JSON schema field "cxKeyVault".
	CxKeyVault KeyVault `json:"cxKeyVault" yaml:"cxKeyVault" mapstructure:"cxKeyVault"`

	// DNS corresponds to the JSON schema field "dns".
	DNS *ConfigSchemaJSONDNS `json:"dns,omitempty" yaml:"dns,omitempty" mapstructure:"dns,omitempty"`

	// Ev2 corresponds to the JSON schema field "ev2".
	Ev2 *ConfigSchemaJSONEv2 `json:"ev2,omitempty" yaml:"ev2,omitempty" mapstructure:"ev2,omitempty"`

	// ExtraVars corresponds to the JSON schema field "extraVars".
	ExtraVars map[string]interface{} `json:"extraVars,omitempty" yaml:"extraVars,omitempty" mapstructure:"extraVars,omitempty"`

	// FirstPartyAppCertificate corresponds to the JSON schema field
	// "firstPartyAppCertificate".
	FirstPartyAppCertificate ConfigSchemaJSONFirstPartyAppCertificate `json:"firstPartyAppCertificate" yaml:"firstPartyAppCertificate" mapstructure:"firstPartyAppCertificate"`

	// FirstPartyAppClientId corresponds to the JSON schema field
	// "firstPartyAppClientId".
	FirstPartyAppClientId string `json:"firstPartyAppClientId" yaml:"firstPartyAppClientId" mapstructure:"firstPartyAppClientId"`

	// Frontend corresponds to the JSON schema field "frontend".
	Frontend ConfigSchemaJSONFrontend `json:"frontend" yaml:"frontend" mapstructure:"frontend"`

	// Geneva corresponds to the JSON schema field "geneva".
	Geneva *ConfigSchemaJSONGeneva `json:"geneva,omitempty" yaml:"geneva,omitempty" mapstructure:"geneva,omitempty"`

	// GenevaActions corresponds to the JSON schema field "genevaActions".
	GenevaActions ConfigSchemaJSONGenevaActions `json:"genevaActions" yaml:"genevaActions" mapstructure:"genevaActions"`

	// Global corresponds to the JSON schema field "global".
	Global ConfigSchemaJSONGlobal `json:"global" yaml:"global" mapstructure:"global"`

	// Hypershift corresponds to the JSON schema field "hypershift".
	Hypershift ConfigSchemaJSONHypershift `json:"hypershift" yaml:"hypershift" mapstructure:"hypershift"`

	// ImageSync corresponds to the JSON schema field "imageSync".
	ImageSync ConfigSchemaJSONImageSync `json:"imageSync" yaml:"imageSync" mapstructure:"imageSync"`

	// Kusto corresponds to the JSON schema field "kusto".
	Kusto *ConfigSchemaJSONKusto `json:"kusto,omitempty" yaml:"kusto,omitempty" mapstructure:"kusto,omitempty"`

	// The principal ID of the cert officer that will be used to manage KV certificate
	// issuers
	KVCertOfficerPrincipalId string `json:"kvCertOfficerPrincipalId" yaml:"kvCertOfficerPrincipalId" mapstructure:"kvCertOfficerPrincipalId"`

	// Log infrastructure configuration
	Logs *ConfigSchemaJSONLogs `json:"logs,omitempty" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// Maestro corresponds to the JSON schema field "maestro".
	Maestro ConfigSchemaJSONMaestro `json:"maestro" yaml:"maestro" mapstructure:"maestro"`

	// Mgmt corresponds to the JSON schema field "mgmt".
	Mgmt ConfigSchemaJSONMgmt `json:"mgmt" yaml:"mgmt" mapstructure:"mgmt"`

	// MgmtKeyVault corresponds to the JSON schema field "mgmtKeyVault".
	MgmtKeyVault KeyVault `json:"mgmtKeyVault" yaml:"mgmtKeyVault" mapstructure:"mgmtKeyVault"`

	// MiMockCertName corresponds to the JSON schema field "miMockCertName".
	MiMockCertName *string `json:"miMockCertName,omitempty" yaml:"miMockCertName,omitempty" mapstructure:"miMockCertName,omitempty"`

	// MiMockClientId corresponds to the JSON schema field "miMockClientId".
	MiMockClientId *string `json:"miMockClientId,omitempty" yaml:"miMockClientId,omitempty" mapstructure:"miMockClientId,omitempty"`

	// MiMockPrincipalId corresponds to the JSON schema field "miMockPrincipalId".
	MiMockPrincipalId *string `json:"miMockPrincipalId,omitempty" yaml:"miMockPrincipalId,omitempty" mapstructure:"miMockPrincipalId,omitempty"`

	// Mise corresponds to the JSON schema field "mise".
	Mise interface{} `json:"mise,omitempty" yaml:"mise,omitempty" mapstructure:"mise,omitempty"`

	// Monitoring corresponds to the JSON schema field "monitoring".
	Monitoring ConfigSchemaJSONMonitoring `json:"monitoring" yaml:"monitoring" mapstructure:"monitoring"`

	// MSIKeyVault corresponds to the JSON schema field "msiKeyVault".
	MSIKeyVault KeyVault `json:"msiKeyVault" yaml:"msiKeyVault" mapstructure:"msiKeyVault"`

	// MSIRp corresponds to the JSON schema field "msiRp".
	MSIRp *ConfigSchemaJSONMSIRp `json:"msiRp,omitempty" yaml:"msiRp,omitempty" mapstructure:"msiRp,omitempty"`

	// OIDC corresponds to the JSON schema field "oidc".
	OIDC ConfigSchemaJSONOIDC `json:"oidc" yaml:"oidc" mapstructure:"oidc"`

	// Pko corresponds to the JSON schema field "pko".
	Pko *ConfigSchemaJSONPko `json:"pko,omitempty" yaml:"pko,omitempty" mapstructure:"pko,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// RegionRG corresponds to the JSON schema field "regionRG".
	RegionRG ResourceGroupName `json:"regionRG" yaml:"regionRG" mapstructure:"regionRG"`

	// ReleaseApprover corresponds to the JSON schema field "releaseApprover".
	ReleaseApprover *ConfigSchemaJSONReleaseApprover `json:"releaseApprover,omitempty" yaml:"releaseApprover,omitempty" mapstructure:"releaseApprover,omitempty"`

	// SecretSyncController corresponds to the JSON schema field
	// "secretSyncController".
	SecretSyncController ConfigSchemaJSONSecretSyncController `json:"secretSyncController" yaml:"secretSyncController" mapstructure:"secretSyncController"`

	// ServiceKeyVault corresponds to the JSON schema field "serviceKeyVault".
	ServiceKeyVault ConfigSchemaJSONServiceKeyVault `json:"serviceKeyVault" yaml:"serviceKeyVault" mapstructure:"serviceKeyVault"`

	// Svc corresponds to the JSON schema field "svc".
	Svc ConfigSchemaJSONSvc `json:"svc" yaml:"svc" mapstructure:"svc"`

	// TenantId corresponds to the JSON schema field "tenantId".
	TenantId *string `json:"tenantId,omitempty" yaml:"tenantId,omitempty" mapstructure:"tenantId,omitempty"`
}

type ConfigSchemaJSONACR struct {
	// OCP corresponds to the JSON schema field "ocp".
	OCP ACR `json:"ocp" yaml:"ocp" mapstructure:"ocp"`

	// Svc corresponds to the JSON schema field "svc".
	Svc ACR `json:"svc" yaml:"svc" mapstructure:"svc"`
}

type ConfigSchemaJSONACRPull struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type ConfigSchemaJSONAcm struct {
	// MCE corresponds to the JSON schema field "mce".
	MCE ConfigSchemaJSONAcmMCE `json:"mce" yaml:"mce" mapstructure:"mce"`
}

type ConfigSchemaJSONAcmMCE struct {
	// Pause reconciliation of ACM MCE resources like CRDs and deployments.
	PauseReconciliation bool `json:"pauseReconciliation" yaml:"pauseReconciliation" mapstructure:"pauseReconciliation"`
}

type ConfigSchemaJSONAdministration struct {
	// ReaderGroupIds corresponds to the JSON schema field "readerGroupIds".
	ReaderGroupIds []string `json:"readerGroupIds" yaml:"readerGroupIds" mapstructure:"readerGroupIds"`
}

type ConfigSchemaJSONArobit struct {
	// Forwarder corresponds to the JSON schema field "forwarder".
	Forwarder ConfigSchemaJSONArobitForwarder `json:"forwarder" yaml:"forwarder" mapstructure:"forwarder"`

	// Mdsd corresponds to the JSON schema field "mdsd".
	Mdsd ConfigSchemaJSONArobitMdsd `json:"mdsd" yaml:"mdsd" mapstructure:"mdsd"`
}

type ConfigSchemaJSONArobitForwarder struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type ConfigSchemaJSONArobitMdsd struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type ConfigSchemaJSONBackend struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type ConfigSchemaJSONBackplaneAPI struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type ConfigSchemaJSONClustersService struct {
	// AzureOperatorsManagedIdentities corresponds to the JSON schema field
	// "azureOperatorsManagedIdentities".
	AzureOperatorsManagedIdentities ConfigSchemaJSONClustersServiceAzureOperatorsManagedIdentities `json:"azureOperatorsManagedIdentities" yaml:"azureOperatorsManagedIdentities" mapstructure:"azureOperatorsManagedIdentities"`

	// Environment corresponds to the JSON schema field "environment".
	Environment string `json:"environment" yaml:"environment" mapstructure:"environment"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S ConfigSchemaJSONClustersServiceK8S `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by CS to interact with Azure
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// Postgres corresponds to the JSON schema field "postgres".
	Postgres Postgres `json:"postgres" yaml:"postgres" mapstructure:"postgres"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type ConfigSchemaJSONClustersServiceAzureOperatorsManagedIdentities struct {
	// CloudControllerManager corresponds to the JSON schema field
	// "cloudControllerManager".
	CloudControllerManager OperatorConfig `json:"cloudControllerManager" yaml:"cloudControllerManager" mapstructure:"cloudControllerManager"`

	// CloudNetworkConfig corresponds to the JSON schema field "cloudNetworkConfig".
	CloudNetworkConfig OperatorConfig `json:"cloudNetworkConfig" yaml:"cloudNetworkConfig" mapstructure:"cloudNetworkConfig"`

	// ClusterAPIAzure corresponds to the JSON schema field "clusterApiAzure".
	ClusterAPIAzure OperatorConfig `json:"clusterApiAzure" yaml:"clusterApiAzure" mapstructure:"clusterApiAzure"`

	// ControlPlane corresponds to the JSON schema field "controlPlane".
	ControlPlane OperatorConfig `json:"controlPlane" yaml:"controlPlane" mapstructure:"controlPlane"`

	// DiskCSIDriver corresponds to the JSON schema field "diskCsiDriver".
	DiskCSIDriver OperatorConfig `json:"diskCsiDriver" yaml:"diskCsiDriver" mapstructure:"diskCsiDriver"`

	// FileCSIDriver corresponds to the JSON schema field "fileCsiDriver".
	FileCSIDriver OperatorConfig `json:"fileCsiDriver" yaml:"fileCsiDriver" mapstructure:"fileCsiDriver"`

	// ImageRegistry corresponds to the JSON schema field "imageRegistry".
	ImageRegistry OperatorConfig `json:"imageRegistry" yaml:"imageRegistry" mapstructure:"imageRegistry"`

	// Ingress corresponds to the JSON schema field "ingress".
	Ingress OperatorConfig `json:"ingress" yaml:"ingress" mapstructure:"ingress"`

	// Kms corresponds to the JSON schema field "kms".
	Kms OperatorConfig `json:"kms" yaml:"kms" mapstructure:"kms"`
}

type ConfigSchemaJSONClustersServiceK8S struct {
	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// ServiceAccountName corresponds to the JSON schema field "serviceAccountName".
	ServiceAccountName string `json:"serviceAccountName" yaml:"serviceAccountName" mapstructure:"serviceAccountName"`
}

type ConfigSchemaJSONDNS struct {
	// The Azure RG that holds the parent DNS zones
	BaseDNSZoneRG ResourceGroupName `json:"baseDnsZoneRG" yaml:"baseDnsZoneRG" mapstructure:"baseDnsZoneRG"`

	// Whether to manage the CX parent zone delegation on the parents parent.
	CxParentZoneDelegation *bool `json:"cxParentZoneDelegation,omitempty" yaml:"cxParentZoneDelegation,omitempty" mapstructure:"cxParentZoneDelegation,omitempty"`

	// The parent DNS zone name for regional HCP cluster DNS zones
	CxParentZoneName string `json:"cxParentZoneName" yaml:"cxParentZoneName" mapstructure:"cxParentZoneName"`

	// The global parent DNS zone name
	ParentZoneName *string `json:"parentZoneName,omitempty" yaml:"parentZoneName,omitempty" mapstructure:"parentZoneName,omitempty"`

	// The regional subdomain to be used to construct the regional hcp and svc zones
	// under their respective parents, e.g. regionalSubdomain.svcParentZoneName
	RegionalSubdomain string `json:"regionalSubdomain" yaml:"regionalSubdomain" mapstructure:"regionalSubdomain"`

	// The parent DNS zone name for regional ARO-HCP infrastructure, e.g. the RP
	SvcParentZoneName string `json:"svcParentZoneName" yaml:"svcParentZoneName" mapstructure:"svcParentZoneName"`
}

type ConfigSchemaJSONEv2 struct {
	// AssistedId corresponds to the JSON schema field "assistedId".
	AssistedId ConfigSchemaJSONEv2AssistedId `json:"assistedId" yaml:"assistedId" mapstructure:"assistedId"`
}

type ConfigSchemaJSONEv2AssistedId struct {
	// ApplicationId corresponds to the JSON schema field "applicationId".
	ApplicationId string `json:"applicationId" yaml:"applicationId" mapstructure:"applicationId"`

	// Certificate corresponds to the JSON schema field "certificate".
	Certificate CertificateRef `json:"certificate" yaml:"certificate" mapstructure:"certificate"`
}

type ConfigSchemaJSONFirstPartyAppCertificate struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Manage corresponds to the JSON schema field "manage".
	Manage bool `json:"manage" yaml:"manage" mapstructure:"manage"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ConfigSchemaJSONFrontend struct {
	// Audit corresponds to the JSON schema field "audit".
	Audit *Audit `json:"audit,omitempty" yaml:"audit,omitempty" mapstructure:"audit,omitempty"`

	// Cert corresponds to the JSON schema field "cert".
	Cert ConfigSchemaJSONFrontendCert `json:"cert" yaml:"cert" mapstructure:"cert"`

	// CosmosDB corresponds to the JSON schema field "cosmosDB".
	CosmosDB ConfigSchemaJSONFrontendCosmosDB `json:"cosmosDB" yaml:"cosmosDB" mapstructure:"cosmosDB"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type ConfigSchemaJSONFrontendCert struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ConfigSchemaJSONFrontendCosmosDB struct {
	// Deploy corresponds to the JSON schema field "deploy".
	Deploy bool `json:"deploy" yaml:"deploy" mapstructure:"deploy"`

	// DisableLocalAuth corresponds to the JSON schema field "disableLocalAuth".
	DisableLocalAuth bool `json:"disableLocalAuth" yaml:"disableLocalAuth" mapstructure:"disableLocalAuth"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode *ZoneRedundantMode `json:"zoneRedundantMode,omitempty" yaml:"zoneRedundantMode,omitempty" mapstructure:"zoneRedundantMode,omitempty"`
}

type ConfigSchemaJSONGeneva struct {
	// Logs corresponds to the JSON schema field "logs".
	Logs ConfigSchemaJSONGenevaLogs `json:"logs" yaml:"logs" mapstructure:"logs"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics ConfigSchemaJSONGenevaMetrics `json:"metrics" yaml:"metrics" mapstructure:"metrics"`

	// PrincipalId corresponds to the JSON schema field "principalId".
	PrincipalId string `json:"principalId" yaml:"principalId" mapstructure:"principalId"`

	// ResourceContributor corresponds to the JSON schema field "resourceContributor".
	ResourceContributor string `json:"resourceContributor" yaml:"resourceContributor" mapstructure:"resourceContributor"`
}

type ConfigSchemaJSONGenevaActions struct {
	// ServiceTag corresponds to the JSON schema field "serviceTag".
	ServiceTag string `json:"serviceTag" yaml:"serviceTag" mapstructure:"serviceTag"`
}

type ConfigSchemaJSONGenevaLogs struct {
	// Administrators corresponds to the JSON schema field "administrators".
	Administrators ConfigSchemaJSONGenevaLogsAdministrators `json:"administrators" yaml:"administrators" mapstructure:"administrators"`

	// Cluster corresponds to the JSON schema field "cluster".
	Cluster ConfigSchemaJSONGenevaLogsCluster `json:"cluster" yaml:"cluster" mapstructure:"cluster"`

	// Environment corresponds to the JSON schema field "environment".
	Environment ConfigSchemaJSONGenevaLogsEnvironment `json:"environment" yaml:"environment" mapstructure:"environment"`

	// Rp corresponds to the JSON schema field "rp".
	Rp ConfigSchemaJSONGenevaLogsRp `json:"rp" yaml:"rp" mapstructure:"rp"`

	// TypeName corresponds to the JSON schema field "typeName".
	TypeName string `json:"typeName" yaml:"typeName" mapstructure:"typeName"`
}

type ConfigSchemaJSONGenevaLogsAdministrators struct {
	// Alias corresponds to the JSON schema field "alias".
	Alias string `json:"alias" yaml:"alias" mapstructure:"alias"`

	// SecurityGroup corresponds to the JSON schema field "securityGroup".
	SecurityGroup string `json:"securityGroup" yaml:"securityGroup" mapstructure:"securityGroup"`
}

type ConfigSchemaJSONGenevaLogsCluster struct {
	// AccountCert corresponds to the JSON schema field "accountCert".
	AccountCert CertificateRef `json:"accountCert" yaml:"accountCert" mapstructure:"accountCert"`

	// AccountName corresponds to the JSON schema field "accountName".
	AccountName string `json:"accountName" yaml:"accountName" mapstructure:"accountName"`
}

type ConfigSchemaJSONGenevaLogsEnvironment string

const ConfigSchemaJSONGenevaLogsEnvironmentBillingProd ConfigSchemaJSONGenevaLogsEnvironment = "BillingProd"
const ConfigSchemaJSONGenevaLogsEnvironmentCaFairfax ConfigSchemaJSONGenevaLogsEnvironment = "CaFairfax"
const ConfigSchemaJSONGenevaLogsEnvironmentCaMooncake ConfigSchemaJSONGenevaLogsEnvironment = "CaMooncake"
const ConfigSchemaJSONGenevaLogsEnvironmentCanary ConfigSchemaJSONGenevaLogsEnvironment = "Canary"
const ConfigSchemaJSONGenevaLogsEnvironmentDiagnosticsProd ConfigSchemaJSONGenevaLogsEnvironment = "DiagnosticsProd"
const ConfigSchemaJSONGenevaLogsEnvironmentExternalProd ConfigSchemaJSONGenevaLogsEnvironment = "ExternalProd"
const ConfigSchemaJSONGenevaLogsEnvironmentFirstPartyProd ConfigSchemaJSONGenevaLogsEnvironment = "FirstPartyProd"
const ConfigSchemaJSONGenevaLogsEnvironmentStage ConfigSchemaJSONGenevaLogsEnvironment = "Stage"
const ConfigSchemaJSONGenevaLogsEnvironmentTest ConfigSchemaJSONGenevaLogsEnvironment = "Test"
const ConfigSchemaJSONGenevaLogsEnvironmentUsNat ConfigSchemaJSONGenevaLogsEnvironment = "UsNat"
const ConfigSchemaJSONGenevaLogsEnvironmentUsSec ConfigSchemaJSONGenevaLogsEnvironment = "UsSec"
type ConfigSchemaJSONGenevaLogsRp struct {
	// AccountCert corresponds to the JSON schema field "accountCert".
	AccountCert CertificateRef `json:"accountCert" yaml:"accountCert" mapstructure:"accountCert"`

	// AccountName corresponds to the JSON schema field "accountName".
	AccountName string `json:"accountName" yaml:"accountName" mapstructure:"accountName"`
}

type ConfigSchemaJSONGenevaMetrics struct {
	// Cluster corresponds to the JSON schema field "cluster".
	Cluster ConfigSchemaJSONGenevaMetricsCluster `json:"cluster" yaml:"cluster" mapstructure:"cluster"`

	// Rp corresponds to the JSON schema field "rp".
	Rp ConfigSchemaJSONGenevaMetricsRp `json:"rp" yaml:"rp" mapstructure:"rp"`
}

type ConfigSchemaJSONGenevaMetricsCluster struct {
	// Account corresponds to the JSON schema field "account".
	Account string `json:"account" yaml:"account" mapstructure:"account"`
}

type ConfigSchemaJSONGenevaMetricsRp struct {
	// Account corresponds to the JSON schema field "account".
	Account string `json:"account" yaml:"account" mapstructure:"account"`
}

type ConfigSchemaJSONGlobal struct {
	// The name of the MSI that will be used for ev2
	GlobalMSIName *string `json:"globalMSIName,omitempty" yaml:"globalMSIName,omitempty" mapstructure:"globalMSIName,omitempty"`

	// KeyVault corresponds to the JSON schema field "keyVault".
	KeyVault KeyVault `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// SafeDnsIntApplication object ID use to delegate child DNS. This is only
	// required for MSFT INT and can be left empty for other targets
	SafeDNSIntAppObjectId *string `json:"safeDnsIntAppObjectId,omitempty" yaml:"safeDnsIntAppObjectId,omitempty" mapstructure:"safeDnsIntAppObjectId,omitempty"`

	// SecretsToSyncDir corresponds to the JSON schema field "secretsToSyncDir".
	SecretsToSyncDir string `json:"secretsToSyncDir" yaml:"secretsToSyncDir" mapstructure:"secretsToSyncDir"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type ConfigSchemaJSONHypershift struct {
	// AdditionalInstallArg corresponds to the JSON schema field
	// "additionalInstallArg".
	AdditionalInstallArg string `json:"additionalInstallArg" yaml:"additionalInstallArg" mapstructure:"additionalInstallArg"`

	// Image corresponds to the JSON schema field "image".
	Image *ContainerImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`
}

type ConfigSchemaJSONImageSync struct {
	// EnvironmentName corresponds to the JSON schema field "environmentName".
	EnvironmentName string `json:"environmentName" yaml:"environmentName" mapstructure:"environmentName"`

	// OcMirror corresponds to the JSON schema field "ocMirror".
	OcMirror ConfigSchemaJSONImageSyncOcMirror `json:"ocMirror" yaml:"ocMirror" mapstructure:"ocMirror"`

	// OndemandSync corresponds to the JSON schema field "ondemandSync".
	OndemandSync *ConfigSchemaJSONImageSyncOndemandSync `json:"ondemandSync,omitempty" yaml:"ondemandSync,omitempty" mapstructure:"ondemandSync,omitempty"`

	// OutboundServiceTags corresponds to the JSON schema field "outboundServiceTags".
	OutboundServiceTags KeyColonValueCSV `json:"outboundServiceTags" yaml:"outboundServiceTags" mapstructure:"outboundServiceTags"`
}

type ConfigSchemaJSONImageSyncOcMirror struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// PullSecretName corresponds to the JSON schema field "pullSecretName".
	PullSecretName string `json:"pullSecretName" yaml:"pullSecretName" mapstructure:"pullSecretName"`
}

type ConfigSchemaJSONImageSyncOndemandSync struct {
	// PullSecretName corresponds to the JSON schema field "pullSecretName".
	PullSecretName string `json:"pullSecretName" yaml:"pullSecretName" mapstructure:"pullSecretName"`
}

type ConfigSchemaJSONKusto struct {
	// Cluster corresponds to the JSON schema field "cluster".
	Cluster string `json:"cluster" yaml:"cluster" mapstructure:"cluster"`

	// ResourceGroup corresponds to the JSON schema field "resourceGroup".
	ResourceGroup string `json:"resourceGroup" yaml:"resourceGroup" mapstructure:"resourceGroup"`
}

// Log infrastructure configuration
type ConfigSchemaJSONLogs struct {
	// Log Analytics configuration
	Loganalytics ConfigSchemaJSONLogsLoganalytics `json:"loganalytics" yaml:"loganalytics" mapstructure:"loganalytics"`

	// Mdsd corresponds to the JSON schema field "mdsd".
	Mdsd ConfigSchemaJSONLogsMdsd `json:"mdsd" yaml:"mdsd" mapstructure:"mdsd"`
}

// Log Analytics configuration
type ConfigSchemaJSONLogsLoganalytics struct {
	// Enable corresponds to the JSON schema field "enable".
	Enable bool `json:"enable" yaml:"enable" mapstructure:"enable"`
}

type ConfigSchemaJSONLogsMdsd struct {
	// Cert corresponds to the JSON schema field "cert".
	Cert ConfigSchemaJSONLogsMdsdCert `json:"cert" yaml:"cert" mapstructure:"cert"`

	// MSIName corresponds to the JSON schema field "msiName".
	MSIName string `json:"msiName" yaml:"msiName" mapstructure:"msiName"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// ServiceAccountName corresponds to the JSON schema field "serviceAccountName".
	ServiceAccountName string `json:"serviceAccountName" yaml:"serviceAccountName" mapstructure:"serviceAccountName"`

	// Geneva logs resources subscriptions
	Subscriptions []interface{} `json:"subscriptions" yaml:"subscriptions" mapstructure:"subscriptions"`
}

type ConfigSchemaJSONLogsMdsdCert struct {
	// Logs certificate issuer
	Issuer string `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Logs certificate name
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Logs certificate type
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type ConfigSchemaJSONMSIRp struct {
	// DataPlaneAudienceResource corresponds to the JSON schema field
	// "dataPlaneAudienceResource".
	DataPlaneAudienceResource string `json:"dataPlaneAudienceResource" yaml:"dataPlaneAudienceResource" mapstructure:"dataPlaneAudienceResource"`
}

type ConfigSchemaJSONMaestro struct {
	// Agent corresponds to the JSON schema field "agent".
	Agent ConfigSchemaJSONMaestroAgent `json:"agent" yaml:"agent" mapstructure:"agent"`

	// Optional SAN base domain for Maestro Eventgrid certificates. If missing,
	// defaults to maestro.${dns.regionalSubdomain}.${dns.svcParentZoneName}
	CertDomain *string `json:"certDomain,omitempty" yaml:"certDomain,omitempty" mapstructure:"certDomain,omitempty"`

	// CertIssuer corresponds to the JSON schema field "certIssuer".
	CertIssuer CertificateIssuer `json:"certIssuer" yaml:"certIssuer" mapstructure:"certIssuer"`

	// EventGrid corresponds to the JSON schema field "eventGrid".
	EventGrid ConfigSchemaJSONMaestroEventGrid `json:"eventGrid" yaml:"eventGrid" mapstructure:"eventGrid"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// Postgres corresponds to the JSON schema field "postgres".
	Postgres Postgres `json:"postgres" yaml:"postgres" mapstructure:"postgres"`

	// RestrictIstioIngress corresponds to the JSON schema field
	// "restrictIstioIngress".
	RestrictIstioIngress bool `json:"restrictIstioIngress" yaml:"restrictIstioIngress" mapstructure:"restrictIstioIngress"`

	// Server corresponds to the JSON schema field "server".
	Server ConfigSchemaJSONMaestroServer `json:"server" yaml:"server" mapstructure:"server"`
}

type ConfigSchemaJSONMaestroAgent struct {
	// ConsumerName corresponds to the JSON schema field "consumerName".
	ConsumerName string `json:"consumerName" yaml:"consumerName" mapstructure:"consumerName"`

	// Loglevel corresponds to the JSON schema field "loglevel".
	Loglevel int64 `json:"loglevel" yaml:"loglevel" mapstructure:"loglevel"`

	// Sidecar corresponds to the JSON schema field "sidecar".
	Sidecar interface{} `json:"sidecar" yaml:"sidecar" mapstructure:"sidecar"`
}

type ConfigSchemaJSONMaestroEventGrid struct {
	// MaxClientSessionsPerAuthName corresponds to the JSON schema field
	// "maxClientSessionsPerAuthName".
	MaxClientSessionsPerAuthName int64 `json:"maxClientSessionsPerAuthName" yaml:"maxClientSessionsPerAuthName" mapstructure:"maxClientSessionsPerAuthName"`

	// Name length should be between 3 and 50 characters in length but we limited to
	// 44 characters so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts.
	// Only alphanumeric letters, digits and the '-' character are allowed in the
	// topic name. Also, the name shouldn't start with the following reserved words:
	// Microsoft-, EventGrid-, System-
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`
}

type ConfigSchemaJSONMaestroServer struct {
	// K8S corresponds to the JSON schema field "k8s".
	K8S ConfigSchemaJSONMaestroServerK8S `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// Loglevel corresponds to the JSON schema field "loglevel".
	Loglevel int64 `json:"loglevel" yaml:"loglevel" mapstructure:"loglevel"`

	// ManagedIdentityName corresponds to the JSON schema field "managedIdentityName".
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// MqttClientName corresponds to the JSON schema field "mqttClientName".
	MqttClientName string `json:"mqttClientName" yaml:"mqttClientName" mapstructure:"mqttClientName"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing *Tracing `json:"tracing,omitempty" yaml:"tracing,omitempty" mapstructure:"tracing,omitempty"`
}

type ConfigSchemaJSONMaestroServerK8S struct {
	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// ServiceAccountName corresponds to the JSON schema field "serviceAccountName".
	ServiceAccountName string `json:"serviceAccountName" yaml:"serviceAccountName" mapstructure:"serviceAccountName"`
}

type ConfigSchemaJSONMgmt struct {
	// AKS corresponds to the JSON schema field "aks".
	AKS AKSConfig `json:"aks" yaml:"aks" mapstructure:"aks"`

	// ApplyKubeletFixes corresponds to the JSON schema field "applyKubeletFixes".
	ApplyKubeletFixes bool `json:"applyKubeletFixes" yaml:"applyKubeletFixes" mapstructure:"applyKubeletFixes"`

	// Jaeger corresponds to the JSON schema field "jaeger".
	Jaeger interface{} `json:"jaeger,omitempty" yaml:"jaeger,omitempty" mapstructure:"jaeger,omitempty"`

	// MDSD / Genevabits log aggregation and shipping configuration
	Logs *AKSLogConfig `json:"logs,omitempty" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Prometheus deployment configuration
	Prometheus Prometheus `json:"prometheus" yaml:"prometheus" mapstructure:"prometheus"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type ConfigSchemaJSONMonitoring struct {
	// DevAlertingEmails corresponds to the JSON schema field "devAlertingEmails".
	DevAlertingEmails *string `json:"devAlertingEmails,omitempty" yaml:"devAlertingEmails,omitempty" mapstructure:"devAlertingEmails,omitempty"`

	// GrafanaMajorVersion corresponds to the JSON schema field "grafanaMajorVersion".
	GrafanaMajorVersion *string `json:"grafanaMajorVersion,omitempty" yaml:"grafanaMajorVersion,omitempty" mapstructure:"grafanaMajorVersion,omitempty"`

	// GrafanaName corresponds to the JSON schema field "grafanaName".
	GrafanaName string `json:"grafanaName" yaml:"grafanaName" mapstructure:"grafanaName"`

	// A space-separated list of Service Principals IDs, Types and their desired
	// grafana roles The format is: <principalId>/<principalType>/<role>, e.g.
	// 12345678-1234-1234-1234-123456789012/Group/Admin
	GrafanaRoles string `json:"grafanaRoles" yaml:"grafanaRoles" mapstructure:"grafanaRoles"`

	// GrafanaZoneRedundantMode corresponds to the JSON schema field
	// "grafanaZoneRedundantMode".
	GrafanaZoneRedundantMode ZoneRedundantMode `json:"grafanaZoneRedundantMode" yaml:"grafanaZoneRedundantMode" mapstructure:"grafanaZoneRedundantMode"`

	// The workspace name should include 4-63 letters, digits or '-'. The '-'
	// shouldn't be the first or the last symbol. We limit the name to 44 characters
	// so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	HcpWorkspaceName string `json:"hcpWorkspaceName" yaml:"hcpWorkspaceName" mapstructure:"hcpWorkspaceName"`

	// Sev1ActionGroupIDs corresponds to the JSON schema field "sev1ActionGroupIDs".
	Sev1ActionGroupIDs *string `json:"sev1ActionGroupIDs,omitempty" yaml:"sev1ActionGroupIDs,omitempty" mapstructure:"sev1ActionGroupIDs,omitempty"`

	// Sev2ActionGroupIDs corresponds to the JSON schema field "sev2ActionGroupIDs".
	Sev2ActionGroupIDs *string `json:"sev2ActionGroupIDs,omitempty" yaml:"sev2ActionGroupIDs,omitempty" mapstructure:"sev2ActionGroupIDs,omitempty"`

	// Sev3ActionGroupIDs corresponds to the JSON schema field "sev3ActionGroupIDs".
	Sev3ActionGroupIDs *string `json:"sev3ActionGroupIDs,omitempty" yaml:"sev3ActionGroupIDs,omitempty" mapstructure:"sev3ActionGroupIDs,omitempty"`

	// Sev4ActionGroupIDs corresponds to the JSON schema field "sev4ActionGroupIDs".
	Sev4ActionGroupIDs *string `json:"sev4ActionGroupIDs,omitempty" yaml:"sev4ActionGroupIDs,omitempty" mapstructure:"sev4ActionGroupIDs,omitempty"`

	// The workspace name should include 4-63 letters, digits or '-'. The '-'
	// shouldn't be the first or the last symbol. We limit the name to 44 characters
	// so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	SvcWorkspaceName string `json:"svcWorkspaceName" yaml:"svcWorkspaceName" mapstructure:"svcWorkspaceName"`
}

type ConfigSchemaJSONOIDC struct {
	// Frontdoor corresponds to the JSON schema field "frontdoor".
	Frontdoor ConfigSchemaJSONOIDCFrontdoor `json:"frontdoor" yaml:"frontdoor" mapstructure:"frontdoor"`

	// StorageAccount corresponds to the JSON schema field "storageAccount".
	StorageAccount ConfigSchemaJSONOIDCStorageAccount `json:"storageAccount" yaml:"storageAccount" mapstructure:"storageAccount"`
}

type ConfigSchemaJSONOIDCFrontdoor struct {
	// KeyVaultName corresponds to the JSON schema field "keyVaultName".
	KeyVaultName ConfigSchemaJSONOIDCFrontdoorKeyVaultName `json:"keyVaultName" yaml:"keyVaultName" mapstructure:"keyVaultName"`

	// MSIName corresponds to the JSON schema field "msiName".
	MSIName string `json:"msiName" yaml:"msiName" mapstructure:"msiName"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Sku corresponds to the JSON schema field "sku".
	Sku ConfigSchemaJSONOIDCFrontdoorSku `json:"sku" yaml:"sku" mapstructure:"sku"`

	// Subdomain corresponds to the JSON schema field "subdomain".
	Subdomain string `json:"subdomain" yaml:"subdomain" mapstructure:"subdomain"`
}

type ConfigSchemaJSONOIDCFrontdoorKeyVaultName interface{}

type ConfigSchemaJSONOIDCFrontdoorSku string

const ConfigSchemaJSONOIDCFrontdoorSkuPremiumAzureFrontDoor ConfigSchemaJSONOIDCFrontdoorSku = "Premium_AzureFrontDoor"
const ConfigSchemaJSONOIDCFrontdoorSkuStandardAzureFrontDoor ConfigSchemaJSONOIDCFrontdoorSku = "Standard_AzureFrontDoor"
type ConfigSchemaJSONOIDCStorageAccount struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Whether the storage account is public or private. If private, it can only be
	// accessed via Azure Front Door
	Public bool `json:"public" yaml:"public" mapstructure:"public"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

type ConfigSchemaJSONPko struct {
	// ImageManager corresponds to the JSON schema field "imageManager".
	ImageManager ContainerImage `json:"imageManager" yaml:"imageManager" mapstructure:"imageManager"`

	// ImagePackage corresponds to the JSON schema field "imagePackage".
	ImagePackage ContainerImage `json:"imagePackage" yaml:"imagePackage" mapstructure:"imagePackage"`

	// RemotePhaseManager corresponds to the JSON schema field "remotePhaseManager".
	RemotePhaseManager ContainerImage `json:"remotePhaseManager" yaml:"remotePhaseManager" mapstructure:"remotePhaseManager"`
}

type ConfigSchemaJSONReleaseApprover struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ConfigSchemaJSONSecretSyncController struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// ProviderImage corresponds to the JSON schema field "providerImage".
	ProviderImage string `json:"providerImage" yaml:"providerImage" mapstructure:"providerImage"`
}

type ConfigSchemaJSONServiceKeyVault struct {
	// AssignNSP corresponds to the JSON schema field "assignNSP".
	AssignNSP *bool `json:"assignNSP,omitempty" yaml:"assignNSP,omitempty" mapstructure:"assignNSP,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name KeyVaultName `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// SoftDelete corresponds to the JSON schema field "softDelete".
	SoftDelete bool `json:"softDelete" yaml:"softDelete" mapstructure:"softDelete"`
}

type ConfigSchemaJSONSvc struct {
	// AKS corresponds to the JSON schema field "aks".
	AKS AKSConfig `json:"aks" yaml:"aks" mapstructure:"aks"`

	// Istio corresponds to the JSON schema field "istio".
	Istio ConfigSchemaJSONSvcIstio `json:"istio" yaml:"istio" mapstructure:"istio"`

	// Jaeger corresponds to the JSON schema field "jaeger".
	Jaeger interface{} `json:"jaeger,omitempty" yaml:"jaeger,omitempty" mapstructure:"jaeger,omitempty"`

	// MDSD / Genevabits log aggregation and shipping configuration
	Logs *AKSLogConfig `json:"logs,omitempty" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Prometheus deployment configuration
	Prometheus *Prometheus `json:"prometheus,omitempty" yaml:"prometheus,omitempty" mapstructure:"prometheus,omitempty"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type ConfigSchemaJSONSvcIstio struct {
	// IngressGatewayIPAddressIPTags corresponds to the JSON schema field
	// "ingressGatewayIPAddressIPTags".
	IngressGatewayIPAddressIPTags *KeyColonValueCSV `json:"ingressGatewayIPAddressIPTags,omitempty" yaml:"ingressGatewayIPAddressIPTags,omitempty" mapstructure:"ingressGatewayIPAddressIPTags,omitempty"`

	// IngressGatewayIPAddressName corresponds to the JSON schema field
	// "ingressGatewayIPAddressName".
	IngressGatewayIPAddressName string `json:"ingressGatewayIPAddressName" yaml:"ingressGatewayIPAddressName" mapstructure:"ingressGatewayIPAddressName"`

	// Latest version of istioctl. This is used to download the istioctl
	IstioctlVersion *string `json:"istioctlVersion,omitempty" yaml:"istioctlVersion,omitempty" mapstructure:"istioctlVersion,omitempty"`

	// The revision tag used in istioctl
	Tag *string `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`

	// The target istio version that will be updated to
	TargetVersion *string `json:"targetVersion,omitempty" yaml:"targetVersion,omitempty" mapstructure:"targetVersion,omitempty"`

	// The current istio version in the AKS cluster as CSV, will need to change to
	// array once tooling is ready
	Versions *string `json:"versions,omitempty" yaml:"versions,omitempty" mapstructure:"versions,omitempty"`
}

type ContainerImage struct {
	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest" yaml:"digest" mapstructure:"digest"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository" yaml:"repository" mapstructure:"repository"`
}

type KeyColonValueCSV string

type KeyVault struct {
	// Name corresponds to the JSON schema field "name".
	Name KeyVaultName `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// SoftDelete corresponds to the JSON schema field "softDelete".
	SoftDelete bool `json:"softDelete" yaml:"softDelete" mapstructure:"softDelete"`
}

// A KV name must be between 3-24 alphanumeric characters. The name must begin with
// a letter, end with a letter or digit, and not contain consecutive hyphens.
type KeyVaultName string

type NSP struct {
	// AccessMode corresponds to the JSON schema field "accessMode".
	AccessMode *NSPAccessMode `json:"accessMode,omitempty" yaml:"accessMode,omitempty" mapstructure:"accessMode,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type NSPAccessMode string

const NSPAccessModeAudit NSPAccessMode = "Audit"
const NSPAccessModeEnforced NSPAccessMode = "Enforced"
const NSPAccessModeLearning NSPAccessMode = "Learning"
type OperatorConfig struct {
	// RoleNames corresponds to the JSON schema field "roleNames".
	RoleNames string `json:"roleNames" yaml:"roleNames" mapstructure:"roleNames"`
}

// A key vault name or an empty string
type OptionalKeyVaultName interface{}

type Postgres struct {
	// DatabaseName corresponds to the JSON schema field "databaseName".
	DatabaseName string `json:"databaseName" yaml:"databaseName" mapstructure:"databaseName"`

	// Deploy corresponds to the JSON schema field "deploy".
	Deploy bool `json:"deploy" yaml:"deploy" mapstructure:"deploy"`

	// MinTLSVersion corresponds to the JSON schema field "minTLSVersion".
	MinTLSVersion PostgresMinTLSVersion `json:"minTLSVersion" yaml:"minTLSVersion" mapstructure:"minTLSVersion"`

	// Name corresponds to the JSON schema field "name".
	Name PostgresName `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// ServerStorageSizeGB corresponds to the JSON schema field "serverStorageSizeGB".
	ServerStorageSizeGB int64 `json:"serverStorageSizeGB" yaml:"serverStorageSizeGB" mapstructure:"serverStorageSizeGB"`

	// ServerVersion corresponds to the JSON schema field "serverVersion".
	ServerVersion string `json:"serverVersion" yaml:"serverVersion" mapstructure:"serverVersion"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

type PostgresMinTLSVersion string

const PostgresMinTLSVersionTLSV12 PostgresMinTLSVersion = "TLSV1.2"
const PostgresMinTLSVersionTLSV13 PostgresMinTLSVersion = "TLSV1.3"
// Server name must only contain lowercase letters, numbers, and hyphens. The
// server name must not start or end in a hyphen. Name must be between 3 be 63
// characters long but we limited to 44 characters so we have a future option to
// use NSP:
// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
type PostgresName string

type Prometheus struct {
	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// NamespaceLabel corresponds to the JSON schema field "namespaceLabel".
	NamespaceLabel *string `json:"namespaceLabel,omitempty" yaml:"namespaceLabel,omitempty" mapstructure:"namespaceLabel,omitempty"`

	// PrometheusConfigReloader corresponds to the JSON schema field
	// "prometheusConfigReloader".
	PrometheusConfigReloader *PrometheusPrometheusConfigReloader `json:"prometheusConfigReloader,omitempty" yaml:"prometheusConfigReloader,omitempty" mapstructure:"prometheusConfigReloader,omitempty"`

	// PrometheusOperator corresponds to the JSON schema field "prometheusOperator".
	PrometheusOperator interface{} `json:"prometheusOperator,omitempty" yaml:"prometheusOperator,omitempty" mapstructure:"prometheusOperator,omitempty"`

	// PrometheusSpec corresponds to the JSON schema field "prometheusSpec".
	PrometheusSpec *PrometheusPrometheusSpec `json:"prometheusSpec,omitempty" yaml:"prometheusSpec,omitempty" mapstructure:"prometheusSpec,omitempty"`
}

type PrometheusPrometheusConfigReloader struct {
	// Image corresponds to the JSON schema field "image".
	Image *ContainerImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`
}

type PrometheusPrometheusSpec struct {
	// Image corresponds to the JSON schema field "image".
	Image *ContainerImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Replicas corresponds to the JSON schema field "replicas".
	Replicas *float64 `json:"replicas,omitempty" yaml:"replicas,omitempty" mapstructure:"replicas,omitempty"`

	// Shards corresponds to the JSON schema field "shards".
	Shards *float64 `json:"shards,omitempty" yaml:"shards,omitempty" mapstructure:"shards,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version *string `json:"version,omitempty" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type ResourceGroupName string

type SubscriptionMetadata struct {
	// AfecFlags corresponds to the JSON schema field "afecFlags".
	AfecFlags []string `json:"afecFlags,omitempty" yaml:"afecFlags,omitempty" mapstructure:"afecFlags,omitempty"`

	// AirsRegisteredUserPrincipalId corresponds to the JSON schema field
	// "airsRegisteredUserPrincipalId".
	AirsRegisteredUserPrincipalId *string `json:"airsRegisteredUserPrincipalId,omitempty" yaml:"airsRegisteredUserPrincipalId,omitempty" mapstructure:"airsRegisteredUserPrincipalId,omitempty"`

	// CertificateDomains corresponds to the JSON schema field "certificateDomains".
	CertificateDomains []string `json:"certificateDomains,omitempty" yaml:"certificateDomains,omitempty" mapstructure:"certificateDomains,omitempty"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName string `json:"displayName" yaml:"displayName" mapstructure:"displayName"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`
}

type Tracing struct {
	// Defines exporter address
	Address string `json:"address" yaml:"address" mapstructure:"address"`

	// Defines which exporter the SDK should use
	Exporter string `json:"exporter" yaml:"exporter" mapstructure:"exporter"`
}

type ZoneRedundantMode string

const ZoneRedundantModeAuto ZoneRedundantMode = "Auto"
const ZoneRedundantModeDisabled ZoneRedundantMode = "Disabled"
const ZoneRedundantModeEnabled ZoneRedundantMode = "Enabled"