// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package arohcpapi

type ACM struct {
	// MCE corresponds to the JSON schema field "mce".
	MCE MCE `json:"mce" yaml:"mce" mapstructure:"mce"`

	// Operator corresponds to the JSON schema field "operator".
	Operator Operator `json:"operator" yaml:"operator" mapstructure:"operator"`
}

type ACR struct {
	// Resource names may contain alpha numeric characters only and must be between 5
	// and 50 characters. We limited the length to 44 characters so we have a future
	// option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// UntaggedImagesRetention corresponds to the JSON schema field
	// "untaggedImagesRetention".
	UntaggedImagesRetention UntaggedImagesRetention `json:"untaggedImagesRetention" yaml:"untaggedImagesRetention" mapstructure:"untaggedImagesRetention"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

type ACRPull struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type AKSAgentPool struct {
	// MaxCount corresponds to the JSON schema field "maxCount".
	MaxCount float64 `json:"maxCount" yaml:"maxCount" mapstructure:"maxCount"`

	// MinCount corresponds to the JSON schema field "minCount".
	MinCount float64 `json:"minCount" yaml:"minCount" mapstructure:"minCount"`

	// OsDiskSizeGB corresponds to the JSON schema field "osDiskSizeGB".
	OsDiskSizeGB float64 `json:"osDiskSizeGB" yaml:"osDiskSizeGB" mapstructure:"osDiskSizeGB"`

	// PoolCount corresponds to the JSON schema field "poolCount".
	PoolCount float64 `json:"poolCount" yaml:"poolCount" mapstructure:"poolCount"`

	// VmSize corresponds to the JSON schema field "vmSize".
	VmSize string `json:"vmSize" yaml:"vmSize" mapstructure:"vmSize"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`

	// Zones to use for the pools.
	Zones Zones `json:"zones" yaml:"zones" mapstructure:"zones"`
}

type AKSConfig struct {
	// ClusterOutboundIPAddressIPTags corresponds to the JSON schema field
	// "clusterOutboundIPAddressIPTags".
	ClusterOutboundIPAddressIPTags KeyColonValueCSV `json:"clusterOutboundIPAddressIPTags" yaml:"clusterOutboundIPAddressIPTags" mapstructure:"clusterOutboundIPAddressIPTags"`

	// EnableSwiftV2Nodepools corresponds to the JSON schema field
	// "enableSwiftV2Nodepools".
	EnableSwiftV2Nodepools *bool `json:"enableSwiftV2Nodepools,omitempty" yaml:"enableSwiftV2Nodepools,omitempty" mapstructure:"enableSwiftV2Nodepools,omitempty"`

	// EnableSwiftV2Vnet corresponds to the JSON schema field "enableSwiftV2Vnet".
	EnableSwiftV2Vnet *bool `json:"enableSwiftV2Vnet,omitempty" yaml:"enableSwiftV2Vnet,omitempty" mapstructure:"enableSwiftV2Vnet,omitempty"`

	// Etcd corresponds to the JSON schema field "etcd".
	Etcd KeyVault `json:"etcd" yaml:"etcd" mapstructure:"etcd"`

	// InfraAgentPool corresponds to the JSON schema field "infraAgentPool".
	InfraAgentPool *AKSAgentPool `json:"infraAgentPool,omitempty" yaml:"infraAgentPool,omitempty" mapstructure:"infraAgentPool,omitempty"`

	// KubernetesVersion corresponds to the JSON schema field "kubernetesVersion".
	KubernetesVersion string `json:"kubernetesVersion" yaml:"kubernetesVersion" mapstructure:"kubernetesVersion"`

	// The name needs to be between 3-63 characters and can contain only letters,
	// numbers, underscores, and hyphens. The name must start and end with a letter or
	// number. We limit the name to 44 characters so we have a future option to use
	// NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// NetworkDataplane corresponds to the JSON schema field "networkDataplane".
	NetworkDataplane NetworkDataplane `json:"networkDataplane" yaml:"networkDataplane" mapstructure:"networkDataplane"`

	// NetworkPolicy corresponds to the JSON schema field "networkPolicy".
	NetworkPolicy NetworkPolicy `json:"networkPolicy" yaml:"networkPolicy" mapstructure:"networkPolicy"`

	// PodSubnetPrefix corresponds to the JSON schema field "podSubnetPrefix".
	PodSubnetPrefix string `json:"podSubnetPrefix" yaml:"podSubnetPrefix" mapstructure:"podSubnetPrefix"`

	// SubnetPrefix corresponds to the JSON schema field "subnetPrefix".
	SubnetPrefix string `json:"subnetPrefix" yaml:"subnetPrefix" mapstructure:"subnetPrefix"`

	// SystemAgentPool corresponds to the JSON schema field "systemAgentPool".
	SystemAgentPool AKSAgentPool `json:"systemAgentPool" yaml:"systemAgentPool" mapstructure:"systemAgentPool"`

	// UserAgentPool corresponds to the JSON schema field "userAgentPool".
	UserAgentPool AKSAgentPool `json:"userAgentPool" yaml:"userAgentPool" mapstructure:"userAgentPool"`

	// VnetAddressPrefix corresponds to the JSON schema field "vnetAddressPrefix".
	VnetAddressPrefix string `json:"vnetAddressPrefix" yaml:"vnetAddressPrefix" mapstructure:"vnetAddressPrefix"`
}

type ARM struct {
	// The application ID of the ARM application.
	ApplicationId string `json:"applicationId" yaml:"applicationId" mapstructure:"applicationId"`

	// The audience FQDN of the ARM applications auth tokens.
	AudienceFQDN string `json:"audienceFQDN" yaml:"audienceFQDN" mapstructure:"audienceFQDN"`

	// The authority/issuer FQDN of the ARM applications auth tokens.
	AuthorityFQDN string `json:"authorityFQDN" yaml:"authorityFQDN" mapstructure:"authorityFQDN"`

	// The label of the ARM policy.
	PolicyLabel string `json:"policyLabel" yaml:"policyLabel" mapstructure:"policyLabel"`

	// The tenant ID where the ARM application lives.
	TenantId string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`
}

type AccessMode string

const AccessModeAudit AccessMode = "Audit"
const AccessModeEnforced AccessMode = "Enforced"
const AccessModeLearning AccessMode = "Learning"

// Geneva Actions related configuration
type Actions struct {
	// AllowedAcisExtensions corresponds to the JSON schema field
	// "allowedAcisExtensions".
	AllowedAcisExtensions string `json:"allowedAcisExtensions" yaml:"allowedAcisExtensions" mapstructure:"allowedAcisExtensions"`

	// This is the app our Geneva Actions will use to talk to the Admin API
	Application EntraApplication `json:"application" yaml:"application" mapstructure:"application"`

	// This is the certificate for the app defined in .application
	Certificate Certificate `json:"certificate" yaml:"certificate" mapstructure:"certificate"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// This is the principal ID of the MSFT owned Geneva Actions identity that will
	// call into our Geneva Actions.
	GenevaActionsPrincipalId string `json:"genevaActionsPrincipalId" yaml:"genevaActionsPrincipalId" mapstructure:"genevaActionsPrincipalId"`

	// Here we store the certificate for the app defined in .application
	KeyVault KeyVault `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// The Service Tag used by Geneva Actions for their egress traffic.
	ServiceTag string `json:"serviceTag" yaml:"serviceTag" mapstructure:"serviceTag"`
}

type AdminAPI struct {
	// Cert corresponds to the JSON schema field "cert".
	Cert Cert `json:"cert" yaml:"cert" mapstructure:"cert"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by the frontend to interact with Azure
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`
}

type Administration struct {
	// ReaderGroupId corresponds to the JSON schema field "readerGroupId".
	ReaderGroupId string `json:"readerGroupId" yaml:"readerGroupId" mapstructure:"readerGroupId"`

	// ReleaseManagementGroupId corresponds to the JSON schema field
	// "releaseManagementGroupId".
	ReleaseManagementGroupId string `json:"releaseManagementGroupId" yaml:"releaseManagementGroupId" mapstructure:"releaseManagementGroupId"`
}

type Administrators struct {
	// Alias corresponds to the JSON schema field "alias".
	Alias []interface{} `json:"alias" yaml:"alias" mapstructure:"alias"`

	// SecurityGroup corresponds to the JSON schema field "securityGroup".
	SecurityGroup string `json:"securityGroup" yaml:"securityGroup" mapstructure:"securityGroup"`
}

type Agent struct {
	// ConsumerName corresponds to the JSON schema field "consumerName".
	ConsumerName string `json:"consumerName" yaml:"consumerName" mapstructure:"consumerName"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// Loglevel corresponds to the JSON schema field "loglevel".
	Loglevel int64 `json:"loglevel" yaml:"loglevel" mapstructure:"loglevel"`

	// ManagedIdentityName corresponds to the JSON schema field "managedIdentityName".
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// Sidecar corresponds to the JSON schema field "sidecar".
	Sidecar interface{} `json:"sidecar" yaml:"sidecar" mapstructure:"sidecar"`
}

type Arobit struct {
	// Forwarder corresponds to the JSON schema field "forwarder".
	Forwarder *Forwarder `json:"forwarder,omitempty" yaml:"forwarder,omitempty" mapstructure:"forwarder,omitempty"`

	// Kusto corresponds to the JSON schema field "kusto".
	Kusto *Kusto `json:"kusto,omitempty" yaml:"kusto,omitempty" mapstructure:"kusto,omitempty"`

	// MDSD corresponds to the JSON schema field "mdsd".
	MDSD *MDSD `json:"mdsd,omitempty" yaml:"mdsd,omitempty" mapstructure:"mdsd,omitempty"`
}

type AssistedId struct {
	// ApplicationId corresponds to the JSON schema field "applicationId".
	ApplicationId string `json:"applicationId" yaml:"applicationId" mapstructure:"applicationId"`

	// Certificate corresponds to the JSON schema field "certificate".
	Certificate CertificateRef `json:"certificate" yaml:"certificate" mapstructure:"certificate"`

	// DstsHost corresponds to the JSON schema field "dstsHost".
	DstsHost *string `json:"dstsHost,omitempty" yaml:"dstsHost,omitempty" mapstructure:"dstsHost,omitempty"`
}

type Aub struct {
	// AccountName corresponds to the JSON schema field "accountName".
	AccountName string `json:"accountName" yaml:"accountName" mapstructure:"accountName"`

	// CloudSuffix corresponds to the JSON schema field "cloudSuffix".
	CloudSuffix string `json:"cloudSuffix" yaml:"cloudSuffix" mapstructure:"cloudSuffix"`
}

type Audit struct {
	// ConnectSocket corresponds to the JSON schema field "connectSocket".
	ConnectSocket bool `json:"connectSocket" yaml:"connectSocket" mapstructure:"connectSocket"`
}

type AzureOperatorsManagedIdentities struct {
	// The role set name refers to a particular cloud specific set of operator role
	// definitions, found in the CS values.yaml file
	RoleSetName RoleSetName `json:"roleSetName" yaml:"roleSetName" mapstructure:"roleSetName"`
}

type AzureRuntimeConfig struct {
	// TlsCertificatesIssuer corresponds to the JSON schema field
	// "tlsCertificatesIssuer".
	TlsCertificatesIssuer CertificateIssuer `json:"tlsCertificatesIssuer" yaml:"tlsCertificatesIssuer" mapstructure:"tlsCertificatesIssuer"`
}

type Backend struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by the backend to interact with Azure
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type BackplaneAPI struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type Billing struct {
	// Aub corresponds to the JSON schema field "aub".
	Aub Aub `json:"aub" yaml:"aub" mapstructure:"aub"`

	// EventHub corresponds to the JSON schema field "eventHub".
	EventHub EventHub `json:"eventHub" yaml:"eventHub" mapstructure:"eventHub"`

	// ImageArtifact corresponds to the JSON schema field "imageArtifact".
	ImageArtifact ImageArtifact `json:"imageArtifact" yaml:"imageArtifact" mapstructure:"imageArtifact"`

	// Kusto corresponds to the JSON schema field "kusto".
	Kusto BillingKusto `json:"kusto" yaml:"kusto" mapstructure:"kusto"`

	// Pav2 corresponds to the JSON schema field "pav2".
	Pav2 Pav2 `json:"pav2" yaml:"pav2" mapstructure:"pav2"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`
}

type BillingKusto struct {
	// ClusterName corresponds to the JSON schema field "clusterName".
	ClusterName string `json:"clusterName" yaml:"clusterName" mapstructure:"clusterName"`

	// ClusterPrincipals corresponds to the JSON schema field "clusterPrincipals".
	ClusterPrincipals []ClusterPrincipals `json:"clusterPrincipals" yaml:"clusterPrincipals" mapstructure:"clusterPrincipals"`

	// DstsGroups corresponds to the JSON schema field "dstsGroups".
	DstsGroups []DstsGroups `json:"dstsGroups" yaml:"dstsGroups" mapstructure:"dstsGroups"`

	// Sku corresponds to the JSON schema field "sku".
	Sku string `json:"sku" yaml:"sku" mapstructure:"sku"`

	// If the latest VM usage event in kusto is older than this threshold compared to
	// the current time, skip deletion checks for billing documents. 0 to disable this
	// check.
	VmUsageStaleThreshold string `json:"vmUsageStaleThreshold" yaml:"vmUsageStaleThreshold" mapstructure:"vmUsageStaleThreshold"`
}

type Cert struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// This is the certificate for the app defined in .application
type Certificate struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Manage corresponds to the JSON schema field "manage".
	Manage bool `json:"manage" yaml:"manage" mapstructure:"manage"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type CertificateIssuer string

const CertificateIssuerOneCertV2PrivateCA CertificateIssuer = "OneCertV2-PrivateCA"
const CertificateIssuerOneCertV2PublicCA CertificateIssuer = "OneCertV2-PublicCA"
const CertificateIssuerSelf CertificateIssuer = "Self"

type CertificateRef struct {
	// KeyVault corresponds to the JSON schema field "keyVault".
	KeyVault KeyVaultName `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ChannelGroups struct {
	// Stable corresponds to the JSON schema field "stable".
	Stable Stable `json:"stable" yaml:"stable" mapstructure:"stable"`
}

type Cluster struct {
	// Account corresponds to the JSON schema field "account".
	Account string `json:"account" yaml:"account" mapstructure:"account"`
}

type ClusterPrincipals struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Role corresponds to the JSON schema field "role".
	Role string `json:"role" yaml:"role" mapstructure:"role"`

	// TenantId corresponds to the JSON schema field "tenantId".
	TenantId string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type ClustersService struct {
	// AzureOperatorsManagedIdentities corresponds to the JSON schema field
	// "azureOperatorsManagedIdentities".
	AzureOperatorsManagedIdentities AzureOperatorsManagedIdentities `json:"azureOperatorsManagedIdentities" yaml:"azureOperatorsManagedIdentities" mapstructure:"azureOperatorsManagedIdentities"`

	// AzureRuntimeConfig corresponds to the JSON schema field "azureRuntimeConfig".
	AzureRuntimeConfig AzureRuntimeConfig `json:"azureRuntimeConfig" yaml:"azureRuntimeConfig" mapstructure:"azureRuntimeConfig"`

	// A comma-separated list of batch processes to execute. If set to an empty
	// string, no batch processes are executed. No whitespace characters are allowed
	// before or after the commas, or at the beginning or end of the list.
	BatchProcesses *string `json:"batchProcesses,omitempty" yaml:"batchProcesses,omitempty" mapstructure:"batchProcesses,omitempty"`

	// If true, batch processes will only log what they would do, without making any
	// changes.
	BatchProcessesDryRun *bool `json:"batchProcessesDryRun,omitempty" yaml:"batchProcessesDryRun,omitempty" mapstructure:"batchProcessesDryRun,omitempty"`

	// DenyAssignments corresponds to the JSON schema field "denyAssignments".
	DenyAssignments DenyAssignments `json:"denyAssignments" yaml:"denyAssignments" mapstructure:"denyAssignments"`

	// If true, debug jobs will be deployed to the cluster. The jobs will be used to
	// debug the CS service.
	DeployDebugJobs *bool `json:"deployDebugJobs,omitempty" yaml:"deployDebugJobs,omitempty" mapstructure:"deployDebugJobs,omitempty"`

	// Environment corresponds to the JSON schema field "environment".
	Environment string `json:"environment" yaml:"environment" mapstructure:"environment"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by CS to interact with Azure
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// OCPVersions corresponds to the JSON schema field "ocpVersions".
	OCPVersions OCPVersions `json:"ocpVersions" yaml:"ocpVersions" mapstructure:"ocpVersions"`

	// Postgres corresponds to the JSON schema field "postgres".
	Postgres Postgres `json:"postgres" yaml:"postgres" mapstructure:"postgres"`

	// The maximum number of HCPs that can be placed on an MC, sadly not configurable
	// per MC
	ProvisionShardClusterLimit *int64 `json:"provisionShardClusterLimit,omitempty" yaml:"provisionShardClusterLimit,omitempty" mapstructure:"provisionShardClusterLimit,omitempty"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type ConfigSchemaJSON struct {
	// ACM corresponds to the JSON schema field "acm".
	ACM *ACM `json:"acm,omitempty" yaml:"acm,omitempty" mapstructure:"acm,omitempty"`

	// ACR corresponds to the JSON schema field "acr".
	ACR *ConfigSchemaJSONACR `json:"acr,omitempty" yaml:"acr,omitempty" mapstructure:"acr,omitempty"`

	// The DNS suffix for Azure Container Registry (e.g., azurecr.io, azurecr.us,
	// azurecr.cn)
	ACRDNSSuffix string `json:"acrDNSSuffix" yaml:"acrDNSSuffix" mapstructure:"acrDNSSuffix"`

	// ACRPull corresponds to the JSON schema field "acrPull".
	ACRPull ACRPull `json:"acrPull" yaml:"acrPull" mapstructure:"acrPull"`

	// AdminAPI corresponds to the JSON schema field "adminApi".
	AdminAPI *AdminAPI `json:"adminApi,omitempty" yaml:"adminApi,omitempty" mapstructure:"adminApi,omitempty"`

	// Administration corresponds to the JSON schema field "administration".
	Administration Administration `json:"administration" yaml:"administration" mapstructure:"administration"`

	// ARMHelperCertName corresponds to the JSON schema field "armHelperCertName".
	ARMHelperCertName *string `json:"armHelperCertName,omitempty" yaml:"armHelperCertName,omitempty" mapstructure:"armHelperCertName,omitempty"`

	// ARMHelperClientId corresponds to the JSON schema field "armHelperClientId".
	ARMHelperClientId *string `json:"armHelperClientId,omitempty" yaml:"armHelperClientId,omitempty" mapstructure:"armHelperClientId,omitempty"`

	// ARMHelperFPAPrincipalId corresponds to the JSON schema field
	// "armHelperFPAPrincipalId".
	ARMHelperFPAPrincipalId *string `json:"armHelperFPAPrincipalId,omitempty" yaml:"armHelperFPAPrincipalId,omitempty" mapstructure:"armHelperFPAPrincipalId,omitempty"`

	// Arobit corresponds to the JSON schema field "arobit".
	Arobit *Arobit `json:"arobit,omitempty" yaml:"arobit,omitempty" mapstructure:"arobit,omitempty"`

	// Whether automation account runs in dry-run mode
	AutomationDryRun *bool `json:"automationDryRun,omitempty" yaml:"automationDryRun,omitempty" mapstructure:"automationDryRun,omitempty"`

	// AzureGeoShortId corresponds to the JSON schema field "azureGeoShortId".
	AzureGeoShortId string `json:"azureGeoShortId" yaml:"azureGeoShortId" mapstructure:"azureGeoShortId"`

	// AzureRegionAvailabilityZoneCount corresponds to the JSON schema field
	// "azureRegionAvailabilityZoneCount".
	AzureRegionAvailabilityZoneCount *int64 `json:"azureRegionAvailabilityZoneCount,omitempty" yaml:"azureRegionAvailabilityZoneCount,omitempty" mapstructure:"azureRegionAvailabilityZoneCount,omitempty"`

	// Backend corresponds to the JSON schema field "backend".
	Backend *Backend `json:"backend,omitempty" yaml:"backend,omitempty" mapstructure:"backend,omitempty"`

	// BackplaneAPI corresponds to the JSON schema field "backplaneAPI".
	BackplaneAPI BackplaneAPI `json:"backplaneAPI" yaml:"backplaneAPI" mapstructure:"backplaneAPI"`

	// Billing corresponds to the JSON schema field "billing".
	Billing *Billing `json:"billing,omitempty" yaml:"billing,omitempty" mapstructure:"billing,omitempty"`

	// Cloud corresponds to the JSON schema field "cloud".
	Cloud *string `json:"cloud,omitempty" yaml:"cloud,omitempty" mapstructure:"cloud,omitempty"`

	// ClustersService corresponds to the JSON schema field "clustersService".
	ClustersService ClustersService `json:"clustersService" yaml:"clustersService" mapstructure:"clustersService"`

	// CxKeyVault corresponds to the JSON schema field "cxKeyVault".
	CxKeyVault KeyVault `json:"cxKeyVault" yaml:"cxKeyVault" mapstructure:"cxKeyVault"`

	// DNS corresponds to the JSON schema field "dns".
	DNS *DNS `json:"dns,omitempty" yaml:"dns,omitempty" mapstructure:"dns,omitempty"`

	// E2E corresponds to the JSON schema field "e2e".
	E2E E2E `json:"e2e" yaml:"e2e" mapstructure:"e2e"`

	// EnvironmentName corresponds to the JSON schema field "environmentName".
	EnvironmentName *string `json:"environmentName,omitempty" yaml:"environmentName,omitempty" mapstructure:"environmentName,omitempty"`

	// Ev2 corresponds to the JSON schema field "ev2".
	Ev2 *Ev2 `json:"ev2,omitempty" yaml:"ev2,omitempty" mapstructure:"ev2,omitempty"`

	// ExtraVars corresponds to the JSON schema field "extraVars".
	ExtraVars map[string]interface{} `json:"extraVars,omitempty" yaml:"extraVars,omitempty" mapstructure:"extraVars,omitempty"`

	// FirstPartyAppCertificate corresponds to the JSON schema field
	// "firstPartyAppCertificate".
	FirstPartyAppCertificate FirstPartyAppCertificate `json:"firstPartyAppCertificate" yaml:"firstPartyAppCertificate" mapstructure:"firstPartyAppCertificate"`

	// FirstPartyAppClientId corresponds to the JSON schema field
	// "firstPartyAppClientId".
	FirstPartyAppClientId string `json:"firstPartyAppClientId" yaml:"firstPartyAppClientId" mapstructure:"firstPartyAppClientId"`

	// Frontend corresponds to the JSON schema field "frontend".
	Frontend Frontend `json:"frontend" yaml:"frontend" mapstructure:"frontend"`

	// Geneva corresponds to the JSON schema field "geneva".
	Geneva *Geneva `json:"geneva,omitempty" yaml:"geneva,omitempty" mapstructure:"geneva,omitempty"`

	// Global corresponds to the JSON schema field "global".
	Global Global `json:"global" yaml:"global" mapstructure:"global"`

	// Hypershift corresponds to the JSON schema field "hypershift".
	Hypershift Hypershift `json:"hypershift" yaml:"hypershift" mapstructure:"hypershift"`

	// ImageSync corresponds to the JSON schema field "imageSync".
	ImageSync ImageSync `json:"imageSync" yaml:"imageSync" mapstructure:"imageSync"`

	// KeyVaultDNSSuffix corresponds to the JSON schema field "keyVaultDNSSuffix".
	KeyVaultDNSSuffix string `json:"keyVaultDNSSuffix" yaml:"keyVaultDNSSuffix" mapstructure:"keyVaultDNSSuffix"`

	// KubeEvents corresponds to the JSON schema field "kubeEvents".
	KubeEvents *KubeEvents `json:"kubeEvents,omitempty" yaml:"kubeEvents,omitempty" mapstructure:"kubeEvents,omitempty"`

	// Kusto corresponds to the JSON schema field "kusto".
	Kusto *ConfigSchemaJSONKusto `json:"kusto,omitempty" yaml:"kusto,omitempty" mapstructure:"kusto,omitempty"`

	// The principal ID of the cert officer that will be used to access KV certificate
	KVCertAccessPrincipalId *string `json:"kvCertAccessPrincipalId,omitempty" yaml:"kvCertAccessPrincipalId,omitempty" mapstructure:"kvCertAccessPrincipalId,omitempty"`

	// The Role ID used for cert access
	KVCertAccessRoleId *string `json:"kvCertAccessRoleId,omitempty" yaml:"kvCertAccessRoleId,omitempty" mapstructure:"kvCertAccessRoleId,omitempty"`

	// The principal ID of the cert officer that will be used to manage KV certificate
	// issuers
	KVCertOfficerPrincipalId string `json:"kvCertOfficerPrincipalId" yaml:"kvCertOfficerPrincipalId" mapstructure:"kvCertOfficerPrincipalId"`

	// Log infrastructure configuration
	Logs *ConfigSchemaJSONLogs `json:"logs,omitempty" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// Maestro corresponds to the JSON schema field "maestro".
	Maestro Maestro `json:"maestro" yaml:"maestro" mapstructure:"maestro"`

	// Mgmt corresponds to the JSON schema field "mgmt".
	Mgmt Mgmt `json:"mgmt" yaml:"mgmt" mapstructure:"mgmt"`

	// MgmtKeyVault corresponds to the JSON schema field "mgmtKeyVault".
	MgmtKeyVault KeyVault `json:"mgmtKeyVault" yaml:"mgmtKeyVault" mapstructure:"mgmtKeyVault"`

	// MiMockCertName corresponds to the JSON schema field "miMockCertName".
	MiMockCertName *string `json:"miMockCertName,omitempty" yaml:"miMockCertName,omitempty" mapstructure:"miMockCertName,omitempty"`

	// MiMockClientId corresponds to the JSON schema field "miMockClientId".
	MiMockClientId *string `json:"miMockClientId,omitempty" yaml:"miMockClientId,omitempty" mapstructure:"miMockClientId,omitempty"`

	// MiMockPrincipalId corresponds to the JSON schema field "miMockPrincipalId".
	MiMockPrincipalId *string `json:"miMockPrincipalId,omitempty" yaml:"miMockPrincipalId,omitempty" mapstructure:"miMockPrincipalId,omitempty"`

	// Mise corresponds to the JSON schema field "mise".
	Mise *Mise `json:"mise,omitempty" yaml:"mise,omitempty" mapstructure:"mise,omitempty"`

	// Monitoring corresponds to the JSON schema field "monitoring".
	Monitoring Monitoring `json:"monitoring" yaml:"monitoring" mapstructure:"monitoring"`

	// MSICredentialsRefresher corresponds to the JSON schema field
	// "msiCredentialsRefresher".
	MSICredentialsRefresher MSICredentialsRefresher `json:"msiCredentialsRefresher" yaml:"msiCredentialsRefresher" mapstructure:"msiCredentialsRefresher"`

	// MSIKeyVault corresponds to the JSON schema field "msiKeyVault".
	MSIKeyVault KeyVault `json:"msiKeyVault" yaml:"msiKeyVault" mapstructure:"msiKeyVault"`

	// MSIRP corresponds to the JSON schema field "msiRp".
	MSIRP MSIRP `json:"msiRp" yaml:"msiRp" mapstructure:"msiRp"`

	// OIDC corresponds to the JSON schema field "oidc".
	OIDC OIDC `json:"oidc" yaml:"oidc" mapstructure:"oidc"`

	// Pko corresponds to the JSON schema field "pko".
	Pko *Pko `json:"pko,omitempty" yaml:"pko,omitempty" mapstructure:"pko,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// Indicates if the region is still in the process of being deployed. When true,
	// various operational features are disabled to prevent issues during deployment,
	// including: ICM alerting. This should be set to false once the region is fully
	// operational
	RegionBuildout bool `json:"regionBuildout" yaml:"regionBuildout" mapstructure:"regionBuildout"`

	// RegionRG corresponds to the JSON schema field "regionRG".
	RegionRG ResourceGroupName `json:"regionRG" yaml:"regionRG" mapstructure:"regionRG"`

	// ReleaseApprover corresponds to the JSON schema field "releaseApprover".
	ReleaseApprover *ReleaseApprover `json:"releaseApprover,omitempty" yaml:"releaseApprover,omitempty" mapstructure:"releaseApprover,omitempty"`

	// RouteMonitorOperator corresponds to the JSON schema field
	// "routeMonitorOperator".
	RouteMonitorOperator *RouteMonitorOperator `json:"routeMonitorOperator,omitempty" yaml:"routeMonitorOperator,omitempty" mapstructure:"routeMonitorOperator,omitempty"`

	// SecretSyncController corresponds to the JSON schema field
	// "secretSyncController".
	SecretSyncController SecretSyncController `json:"secretSyncController" yaml:"secretSyncController" mapstructure:"secretSyncController"`

	// ServiceKeyVault corresponds to the JSON schema field "serviceKeyVault".
	ServiceKeyVault ServiceKeyVault `json:"serviceKeyVault" yaml:"serviceKeyVault" mapstructure:"serviceKeyVault"`

	// Svc corresponds to the JSON schema field "svc".
	Svc Svc `json:"svc" yaml:"svc" mapstructure:"svc"`

	// TenantId corresponds to the JSON schema field "tenantId".
	TenantId *string `json:"tenantId,omitempty" yaml:"tenantId,omitempty" mapstructure:"tenantId,omitempty"`
}

type ConfigSchemaJSONACR struct {
	// OCP corresponds to the JSON schema field "ocp".
	OCP ACR `json:"ocp" yaml:"ocp" mapstructure:"ocp"`

	// Svc corresponds to the JSON schema field "svc".
	Svc ACR `json:"svc" yaml:"svc" mapstructure:"svc"`
}

type ConfigSchemaJSONKusto struct {
	// AdminGroups corresponds to the JSON schema field "adminGroups".
	AdminGroups string `json:"adminGroups" yaml:"adminGroups" mapstructure:"adminGroups"`

	// DEPRECATED, for backward compatibility only
	Cluster *string `json:"cluster,omitempty" yaml:"cluster,omitempty" mapstructure:"cluster,omitempty"`

	// DEPRECATED, for backward compatibility only
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// DEPRECATED, for backward compatibility only
	EnvironmentName *string `json:"environmentName,omitempty" yaml:"environmentName,omitempty" mapstructure:"environmentName,omitempty"`

	// HostedControlPlaneLogsDatabase corresponds to the JSON schema field
	// "hostedControlPlaneLogsDatabase".
	HostedControlPlaneLogsDatabase string `json:"hostedControlPlaneLogsDatabase" yaml:"hostedControlPlaneLogsDatabase" mapstructure:"hostedControlPlaneLogsDatabase"`

	// DEPRECATED, for backward compatibility only
	IngestionUrl *string `json:"ingestionUrl,omitempty" yaml:"ingestionUrl,omitempty" mapstructure:"ingestionUrl,omitempty"`

	// Name of the kusto cluster. Must begin with a letter and contain between 4 and
	// 22 lowercase alphanumeric characters.
	KustoName string `json:"kustoName" yaml:"kustoName" mapstructure:"kustoName"`

	// ManageInstance corresponds to the JSON schema field "manageInstance".
	ManageInstance bool `json:"manageInstance" yaml:"manageInstance" mapstructure:"manageInstance"`

	// DEPRECATED, for backward compatibility only
	ResourceGroup *string `json:"resourceGroup,omitempty" yaml:"resourceGroup,omitempty" mapstructure:"resourceGroup,omitempty"`

	// RG corresponds to the JSON schema field "rg".
	RG *string `json:"rg,omitempty" yaml:"rg,omitempty" mapstructure:"rg,omitempty"`

	// ServiceLogsDatabase corresponds to the JSON schema field "serviceLogsDatabase".
	ServiceLogsDatabase string `json:"serviceLogsDatabase" yaml:"serviceLogsDatabase" mapstructure:"serviceLogsDatabase"`

	// Sku corresponds to the JSON schema field "sku".
	Sku string `json:"sku" yaml:"sku" mapstructure:"sku"`

	// Tier corresponds to the JSON schema field "tier".
	Tier string `json:"tier" yaml:"tier" mapstructure:"tier"`

	// ViewerGroups corresponds to the JSON schema field "viewerGroups".
	ViewerGroups string `json:"viewerGroups" yaml:"viewerGroups" mapstructure:"viewerGroups"`
}

// Log infrastructure configuration
type ConfigSchemaJSONLogs struct {
	// Log Analytics configuration
	Loganalytics Loganalytics `json:"loganalytics" yaml:"loganalytics" mapstructure:"loganalytics"`

	// MDSD corresponds to the JSON schema field "mdsd".
	MDSD LogsMDSD `json:"mdsd" yaml:"mdsd" mapstructure:"mdsd"`
}

type ContainerImage struct {
	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest" yaml:"digest" mapstructure:"digest"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository" yaml:"repository" mapstructure:"repository"`
}

type ContainerImageSha struct {
	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository string `json:"repository" yaml:"repository" mapstructure:"repository"`

	// Sha corresponds to the JSON schema field "sha".
	Sha string `json:"sha" yaml:"sha" mapstructure:"sha"`
}

type ContainerResources struct {
	// Limits corresponds to the JSON schema field "limits".
	Limits *Resources `json:"limits,omitempty" yaml:"limits,omitempty" mapstructure:"limits,omitempty"`

	// Requests corresponds to the JSON schema field "requests".
	Requests *Resources `json:"requests,omitempty" yaml:"requests,omitempty" mapstructure:"requests,omitempty"`
}

type ContainerizedDb struct {
	// Image corresponds to the JSON schema field "image".
	Image *string `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// PvcCapacity corresponds to the JSON schema field "pvcCapacity".
	PvcCapacity *string `json:"pvcCapacity,omitempty" yaml:"pvcCapacity,omitempty" mapstructure:"pvcCapacity,omitempty"`
}

type CosmosDB struct {
	// Deploy corresponds to the JSON schema field "deploy".
	Deploy bool `json:"deploy" yaml:"deploy" mapstructure:"deploy"`

	// DisableLocalAuth corresponds to the JSON schema field "disableLocalAuth".
	DisableLocalAuth bool `json:"disableLocalAuth" yaml:"disableLocalAuth" mapstructure:"disableLocalAuth"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode *ZoneRedundantMode `json:"zoneRedundantMode,omitempty" yaml:"zoneRedundantMode,omitempty" mapstructure:"zoneRedundantMode,omitempty"`
}

type Csv string

type DNS struct {
	// The Azure RG that holds the parent DNS zones
	BaseDNSZoneRG ResourceGroupName `json:"baseDnsZoneRG" yaml:"baseDnsZoneRG" mapstructure:"baseDnsZoneRG"`

	// The parent DNS zone name for regional HCP cluster DNS zones
	CxParentZoneName string `json:"cxParentZoneName" yaml:"cxParentZoneName" mapstructure:"cxParentZoneName"`

	// The global certificates domain
	GlobalCertificatesDomain string `json:"globalCertificatesDomain" yaml:"globalCertificatesDomain" mapstructure:"globalCertificatesDomain"`

	// The global parent DNS zone name
	ParentZoneName *string `json:"parentZoneName,omitempty" yaml:"parentZoneName,omitempty" mapstructure:"parentZoneName,omitempty"`

	// The regional subdomain to be used to construct the regional hcp and svc zones
	// under their respective parents, e.g. regionalSubdomain.svcParentZoneName
	RegionalSubdomain string `json:"regionalSubdomain" yaml:"regionalSubdomain" mapstructure:"regionalSubdomain"`

	// The parent DNS zone name for regional ARO-HCP infrastructure, e.g. the RP
	SvcParentZoneName string `json:"svcParentZoneName" yaml:"svcParentZoneName" mapstructure:"svcParentZoneName"`
}

type DefaultVersion struct {
	// Version corresponds to the JSON schema field "version".
	Version SemVer `json:"version" yaml:"version" mapstructure:"version"`
}

type DenyAssignments string

const DenyAssignmentsDisabled DenyAssignments = "disabled"
const DenyAssignmentsEnabled DenyAssignments = "enabled"

type DstsGroups struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type E2E struct {
	// Prow corresponds to the JSON schema field "prow".
	Prow Prow `json:"prow" yaml:"prow" mapstructure:"prow"`

	// RegionTest corresponds to the JSON schema field "regionTest".
	RegionTest RegionTest `json:"regionTest" yaml:"regionTest" mapstructure:"regionTest"`
}

type EntraApplication struct {
	// Manage corresponds to the JSON schema field "manage".
	Manage *bool `json:"manage,omitempty" yaml:"manage,omitempty" mapstructure:"manage,omitempty"`

	// The name of the application. Needs to be unique within the tenant.
	// https://eng.ms/docs/microsoft-security/identity/auth/auth-sts-protocols/ests/ests-troubleshooting-guides/tsgs/3p-apps-build-out-automation/gotchas-and-known-issues
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// OwnerIds corresponds to the JSON schema field "ownerIds".
	OwnerIds Csv `json:"ownerIds" yaml:"ownerIds" mapstructure:"ownerIds"`

	// UseSNI corresponds to the JSON schema field "useSNI".
	UseSNI *bool `json:"useSNI,omitempty" yaml:"useSNI,omitempty" mapstructure:"useSNI,omitempty"`
}

type Environment string

const EnvironmentBillingProd Environment = "BillingProd"
const EnvironmentCaFairfax Environment = "CaFairfax"
const EnvironmentCaMooncake Environment = "CaMooncake"
const EnvironmentCanary Environment = "Canary"
const EnvironmentDiagnosticsProd Environment = "DiagnosticsProd"
const EnvironmentExternalProd Environment = "ExternalProd"
const EnvironmentFirstPartyProd Environment = "FirstPartyProd"
const EnvironmentStage Environment = "Stage"
const EnvironmentTest Environment = "Test"
const EnvironmentUsNat Environment = "UsNat"
const EnvironmentUsSec Environment = "UsSec"

type Ev2 struct {
	// AssistedId corresponds to the JSON schema field "assistedId".
	AssistedId AssistedId `json:"assistedId" yaml:"assistedId" mapstructure:"assistedId"`
}

type EventGrid struct {
	// MaxClientSessionsPerAuthName corresponds to the JSON schema field
	// "maxClientSessionsPerAuthName".
	MaxClientSessionsPerAuthName int64 `json:"maxClientSessionsPerAuthName" yaml:"maxClientSessionsPerAuthName" mapstructure:"maxClientSessionsPerAuthName"`

	// Name length should be between 3 and 50 characters in length but we limited to
	// 44 characters so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts.
	// Only alphanumeric letters, digits and the '-' character are allowed in the
	// topic name. Also, the name shouldn't start with the following reserved words:
	// Microsoft-, EventGrid-, System-
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`
}

type EventHub struct {
	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// ResourceGroupName corresponds to the JSON schema field "resourceGroupName".
	ResourceGroupName string `json:"resourceGroupName" yaml:"resourceGroupName" mapstructure:"resourceGroupName"`

	// SubscriptionId corresponds to the JSON schema field "subscriptionId".
	SubscriptionId string `json:"subscriptionId" yaml:"subscriptionId" mapstructure:"subscriptionId"`
}

type FirstPartyAppCertificate struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Manage corresponds to the JSON schema field "manage".
	Manage bool `json:"manage" yaml:"manage" mapstructure:"manage"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type Forwarder struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type Frontdoor struct {
	// KeyVault corresponds to the JSON schema field "keyVault".
	KeyVault KeyVault `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// Manage corresponds to the JSON schema field "manage".
	Manage bool `json:"manage" yaml:"manage" mapstructure:"manage"`

	// MSIName corresponds to the JSON schema field "msiName".
	MSIName string `json:"msiName" yaml:"msiName" mapstructure:"msiName"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Sku corresponds to the JSON schema field "sku".
	Sku Sku `json:"sku" yaml:"sku" mapstructure:"sku"`

	// Subdomain corresponds to the JSON schema field "subdomain".
	Subdomain string `json:"subdomain" yaml:"subdomain" mapstructure:"subdomain"`

	// UseManagedCertificates corresponds to the JSON schema field
	// "useManagedCertificates".
	UseManagedCertificates bool `json:"useManagedCertificates" yaml:"useManagedCertificates" mapstructure:"useManagedCertificates"`
}

type Frontend struct {
	// Audit corresponds to the JSON schema field "audit".
	Audit *Audit `json:"audit,omitempty" yaml:"audit,omitempty" mapstructure:"audit,omitempty"`

	// Cert corresponds to the JSON schema field "cert".
	Cert FrontendCert `json:"cert" yaml:"cert" mapstructure:"cert"`

	// CosmosDB corresponds to the JSON schema field "cosmosDB".
	CosmosDB CosmosDB `json:"cosmosDB" yaml:"cosmosDB" mapstructure:"cosmosDB"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by the frontend to interact with Azure
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type FrontendCert struct {
	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type Geneva struct {
	// Geneva Actions related configuration
	Actions Actions `json:"actions" yaml:"actions" mapstructure:"actions"`

	// Logs corresponds to the JSON schema field "logs".
	Logs Logs `json:"logs" yaml:"logs" mapstructure:"logs"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics Metrics `json:"metrics" yaml:"metrics" mapstructure:"metrics"`

	// PrincipalId corresponds to the JSON schema field "principalId".
	PrincipalId string `json:"principalId" yaml:"principalId" mapstructure:"principalId"`

	// ResourceContributor corresponds to the JSON schema field "resourceContributor".
	ResourceContributor string `json:"resourceContributor" yaml:"resourceContributor" mapstructure:"resourceContributor"`
}

type GenevaActions struct {
	// The audience FQDN of the Geneva Actions applications auth tokens.
	AudienceFQDN string `json:"audienceFQDN" yaml:"audienceFQDN" mapstructure:"audienceFQDN"`

	// The authority/issuer FQDN of the Geneva Actions applications auth tokens.
	AuthorityFQDN string `json:"authorityFQDN" yaml:"authorityFQDN" mapstructure:"authorityFQDN"`

	// The label of the Geneva Actions policy.
	PolicyLabel string `json:"policyLabel" yaml:"policyLabel" mapstructure:"policyLabel"`
}

type GenevaLogsAccount struct {
	// AccountName corresponds to the JSON schema field "accountName".
	AccountName string `json:"accountName" yaml:"accountName" mapstructure:"accountName"`

	// Geneva logs account namespace configuration version
	ConfigVersion string `json:"configVersion" yaml:"configVersion" mapstructure:"configVersion"`

	// Geneva logs account namespace
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// Geneva logs account certificate SAN
	SAN string `json:"san" yaml:"san" mapstructure:"san"`

	// Name of the cerificate created and hostname in cert. Must match host in SAN
	SecretName string `json:"secretName" yaml:"secretName" mapstructure:"secretName"`
}

type Global struct {
	// Billing corresponds to the JSON schema field "billing".
	Billing GlobalBilling `json:"billing" yaml:"billing" mapstructure:"billing"`

	// The ID of the role assignment given to the global MSI to deploy our service.
	ContributorRoleId *string `json:"contributorRoleId,omitempty" yaml:"contributorRoleId,omitempty" mapstructure:"contributorRoleId,omitempty"`

	// The name of the MSI that will be used for deployments.
	GlobalMSIName *string `json:"globalMSIName,omitempty" yaml:"globalMSIName,omitempty" mapstructure:"globalMSIName,omitempty"`

	// KeyVault corresponds to the JSON schema field "keyVault".
	KeyVault KeyVault `json:"keyVault" yaml:"keyVault" mapstructure:"keyVault"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// SafeDnsIntApplication object ID use to delegate child DNS. This is only
	// required for MSFT INT and can be left empty for other targets
	SafeDNSIntAppObjectId *string `json:"safeDnsIntAppObjectId,omitempty" yaml:"safeDnsIntAppObjectId,omitempty" mapstructure:"safeDnsIntAppObjectId,omitempty"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type GlobalBilling struct {
	// Digest corresponds to the JSON schema field "digest".
	Digest string `json:"digest" yaml:"digest" mapstructure:"digest"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`
}

type HcpBackups struct {
	// StorageAccount corresponds to the JSON schema field "storageAccount".
	StorageAccount *StorageAccount `json:"storageAccount,omitempty" yaml:"storageAccount,omitempty" mapstructure:"storageAccount,omitempty"`

	// StorageAccountContainerName corresponds to the JSON schema field
	// "storageAccountContainerName".
	StorageAccountContainerName *string `json:"storageAccountContainerName,omitempty" yaml:"storageAccountContainerName,omitempty" mapstructure:"storageAccountContainerName,omitempty"`
}

type Hypershift struct {
	// AdditionalInstallArg corresponds to the JSON schema field
	// "additionalInstallArg".
	AdditionalInstallArg string `json:"additionalInstallArg" yaml:"additionalInstallArg" mapstructure:"additionalInstallArg"`

	// Image corresponds to the JSON schema field "image".
	Image *ContainerImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// SharedIngressIPTag corresponds to the JSON schema field "sharedIngressIPTag".
	SharedIngressIPTag *SharedIngressIPTag `json:"sharedIngressIPTag,omitempty" yaml:"sharedIngressIPTag,omitempty" mapstructure:"sharedIngressIPTag,omitempty"`
}

type Icm struct {
	// ICM connection id
	ConnectionId string `json:"connectionId" yaml:"connectionId" mapstructure:"connectionId"`

	// ICM connection Name
	ConnectionName string `json:"connectionName" yaml:"connectionName" mapstructure:"connectionName"`

	// ICM environment
	Environment string `json:"environment" yaml:"environment" mapstructure:"environment"`

	// ManageConnection corresponds to the JSON schema field "manageConnection".
	ManageConnection *bool `json:"manageConnection,omitempty" yaml:"manageConnection,omitempty" mapstructure:"manageConnection,omitempty"`

	// Msft corresponds to the JSON schema field "msft".
	Msft *IcmConnection `json:"msft,omitempty" yaml:"msft,omitempty" mapstructure:"msft,omitempty"`

	// Sl corresponds to the JSON schema field "sl".
	Sl IcmConnection `json:"sl" yaml:"sl" mapstructure:"sl"`

	// Sre corresponds to the JSON schema field "sre".
	Sre IcmConnection `json:"sre" yaml:"sre" mapstructure:"sre"`
}

type IcmConnection struct {
	// Name of the ICM Action Group
	ActionGroupName string `json:"actionGroupName" yaml:"actionGroupName" mapstructure:"actionGroupName"`

	// Name of the ICM Action Group
	ActionGroupShortName string `json:"actionGroupShortName" yaml:"actionGroupShortName" mapstructure:"actionGroupShortName"`

	// ICM automitigation enabled ID
	AutomitigationEnabled string `json:"automitigationEnabled" yaml:"automitigationEnabled" mapstructure:"automitigationEnabled"`

	// ICM routing ID
	RoutingId string `json:"routingId" yaml:"routingId" mapstructure:"routingId"`
}

type ImageArtifact struct {
	// AdoProject corresponds to the JSON schema field "adoProject".
	AdoProject string `json:"adoProject" yaml:"adoProject" mapstructure:"adoProject"`

	// ArtifactName corresponds to the JSON schema field "artifactName".
	ArtifactName string `json:"artifactName" yaml:"artifactName" mapstructure:"artifactName"`

	// BuildId corresponds to the JSON schema field "buildId".
	BuildId int64 `json:"buildId" yaml:"buildId" mapstructure:"buildId"`
}

type ImageSync struct {
	// EnvironmentName corresponds to the JSON schema field "environmentName".
	EnvironmentName string `json:"environmentName" yaml:"environmentName" mapstructure:"environmentName"`

	// OcMirror corresponds to the JSON schema field "ocMirror".
	OcMirror OcMirror `json:"ocMirror" yaml:"ocMirror" mapstructure:"ocMirror"`

	// OndemandSync corresponds to the JSON schema field "ondemandSync".
	OndemandSync OndemandSync `json:"ondemandSync" yaml:"ondemandSync" mapstructure:"ondemandSync"`

	// OutboundServiceTags corresponds to the JSON schema field "outboundServiceTags".
	OutboundServiceTags KeyColonValueCSV `json:"outboundServiceTags" yaml:"outboundServiceTags" mapstructure:"outboundServiceTags"`
}

// THIS IS CURRENTLY NOT COMPATIBLE WITH SERVICE-STATUS. IntOrString is a type that
// can hold an int32 or a string.  When used in JSON or YAML marshalling and
// unmarshalling, it produces or consumes the inner type. This allows you to have,
// for example, a JSON field that can accept a name or number.
type IntOrString interface{}

type Istio struct {
	// IngressGatewayIPAddressIPTags corresponds to the JSON schema field
	// "ingressGatewayIPAddressIPTags".
	IngressGatewayIPAddressIPTags *KeyColonValueCSV `json:"ingressGatewayIPAddressIPTags,omitempty" yaml:"ingressGatewayIPAddressIPTags,omitempty" mapstructure:"ingressGatewayIPAddressIPTags,omitempty"`

	// IngressGatewayIPAddressName corresponds to the JSON schema field
	// "ingressGatewayIPAddressName".
	IngressGatewayIPAddressName string `json:"ingressGatewayIPAddressName" yaml:"ingressGatewayIPAddressName" mapstructure:"ingressGatewayIPAddressName"`

	// Latest version of istioctl. This is used to download the istioctl
	IstioctlVersion *string `json:"istioctlVersion,omitempty" yaml:"istioctlVersion,omitempty" mapstructure:"istioctlVersion,omitempty"`

	// The revision tag used in istioctl
	Tag *string `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`

	// The target istio version that will be updated to
	TargetVersion *string `json:"targetVersion,omitempty" yaml:"targetVersion,omitempty" mapstructure:"targetVersion,omitempty"`

	// The current istio version in the AKS cluster as CSV, will need to change to
	// array once tooling is ready
	Versions *string `json:"versions,omitempty" yaml:"versions,omitempty" mapstructure:"versions,omitempty"`
}

type K8SDeployment struct {
	// DeploymentStrategy corresponds to the JSON schema field "deploymentStrategy".
	DeploymentStrategy *K8SDeploymentStrategy `json:"deploymentStrategy,omitempty" yaml:"deploymentStrategy,omitempty" mapstructure:"deploymentStrategy,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace NamespaceName `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// Replicas corresponds to the JSON schema field "replicas".
	Replicas *float64 `json:"replicas,omitempty" yaml:"replicas,omitempty" mapstructure:"replicas,omitempty"`

	// ServiceAccountName corresponds to the JSON schema field "serviceAccountName".
	ServiceAccountName ServiceAccountName `json:"serviceAccountName" yaml:"serviceAccountName" mapstructure:"serviceAccountName"`
}

type K8SDeploymentStrategy struct {
	// Rolling update config params
	RollingUpdate *RollingUpdate `json:"rollingUpdate,omitempty" yaml:"rollingUpdate,omitempty" mapstructure:"rollingUpdate,omitempty"`
}

// Spec to control the desired behavior of rolling update.
type K8SRollingUpdateDeploymentStrategy struct {
	// The maximum number of pods that can be scheduled above the desired number of
	// pods. Value can be an absolute number (ex: 5) or a percentage of desired pods
	// (ex: 10%). This can not be 0 if MaxUnavailable is 0. Absolute number is
	// calculated from percentage by rounding up. Defaults to 25%. Example: when this
	// is set to 30%, the new ReplicaSet can be scaled up immediately when the rolling
	// update starts, such that the total number of old and new pods do not exceed
	// 130% of desired pods. Once old pods have been killed, new ReplicaSet can be
	// scaled up further, ensuring that total number of pods running at any time
	// during the update is at most 130% of desired pods.
	MaxSurge interface{} `json:"maxSurge,omitempty" yaml:"maxSurge,omitempty" mapstructure:"maxSurge,omitempty"`

	// The maximum number of pods that can be unavailable during the update. Value can
	// be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%).
	// Absolute number is calculated from percentage by rounding down. This can not be
	// 0 if MaxSurge is 0. Defaults to 25%. Example: when this is set to 30%, the old
	// ReplicaSet can be scaled down to 70% of desired pods immediately when the
	// rolling update starts. Once new pods are ready, old ReplicaSet can be scaled
	// down further, followed by scaling up the new ReplicaSet, ensuring that the
	// total number of pods available at all times during the update is at least 70%
	// of desired pods.
	MaxUnavailable interface{} `json:"maxUnavailable,omitempty" yaml:"maxUnavailable,omitempty" mapstructure:"maxUnavailable,omitempty"`
}

type KeyColonValueCSV string

type KeyVault struct {
	// Name corresponds to the JSON schema field "name".
	Name KeyVaultName `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// SoftDelete corresponds to the JSON schema field "softDelete".
	SoftDelete bool `json:"softDelete" yaml:"softDelete" mapstructure:"softDelete"`

	// TagKey corresponds to the JSON schema field "tagKey".
	TagKey string `json:"tagKey" yaml:"tagKey" mapstructure:"tagKey"`

	// TagValue corresponds to the JSON schema field "tagValue".
	TagValue string `json:"tagValue" yaml:"tagValue" mapstructure:"tagValue"`
}

// A KV name must be between 3-24 alphanumeric characters. The name must begin with
// a letter, end with a letter or digit, and not contain consecutive hyphens.
type KeyVaultName string

type KubeEvents struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type KubeStateMetrics struct {
	// Image corresponds to the JSON schema field "image".
	Image *ContainerImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`
}

type Kusto struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// EnvironmentName corresponds to the JSON schema field "environmentName".
	EnvironmentName string `json:"environmentName" yaml:"environmentName" mapstructure:"environmentName"`
}

// Log Analytics configuration
type Loganalytics struct {
	// Enable corresponds to the JSON schema field "enable".
	Enable bool `json:"enable" yaml:"enable" mapstructure:"enable"`
}

type Logs struct {
	// AdminCertName corresponds to the JSON schema field "adminCertName".
	AdminCertName *string `json:"adminCertName,omitempty" yaml:"adminCertName,omitempty" mapstructure:"adminCertName,omitempty"`

	// AdminCertificateDomain corresponds to the JSON schema field
	// "adminCertificateDomain".
	AdminCertificateDomain *string `json:"adminCertificateDomain,omitempty" yaml:"adminCertificateDomain,omitempty" mapstructure:"adminCertificateDomain,omitempty"`

	// Administrators corresponds to the JSON schema field "administrators".
	Administrators Administrators `json:"administrators" yaml:"administrators" mapstructure:"administrators"`

	// CertificateDomain corresponds to the JSON schema field "certificateDomain".
	CertificateDomain *string `json:"certificateDomain,omitempty" yaml:"certificateDomain,omitempty" mapstructure:"certificateDomain,omitempty"`

	// CertificateIssuer corresponds to the JSON schema field "certificateIssuer".
	CertificateIssuer *CertificateIssuer `json:"certificateIssuer,omitempty" yaml:"certificateIssuer,omitempty" mapstructure:"certificateIssuer,omitempty"`

	// Cluster corresponds to the JSON schema field "cluster".
	Cluster *GenevaLogsAccount `json:"cluster,omitempty" yaml:"cluster,omitempty" mapstructure:"cluster,omitempty"`

	// Environment corresponds to the JSON schema field "environment".
	Environment Environment `json:"environment" yaml:"environment" mapstructure:"environment"`

	// ManageCertificates corresponds to the JSON schema field "manageCertificates".
	ManageCertificates *bool `json:"manageCertificates,omitempty" yaml:"manageCertificates,omitempty" mapstructure:"manageCertificates,omitempty"`

	// RP corresponds to the JSON schema field "rp".
	RP *GenevaLogsAccount `json:"rp,omitempty" yaml:"rp,omitempty" mapstructure:"rp,omitempty"`

	// TypeName corresponds to the JSON schema field "typeName".
	TypeName string `json:"typeName" yaml:"typeName" mapstructure:"typeName"`
}

type LogsMDSD struct {
	// Cert corresponds to the JSON schema field "cert".
	Cert MDSDCert `json:"cert" yaml:"cert" mapstructure:"cert"`

	// MSIName corresponds to the JSON schema field "msiName".
	MSIName string `json:"msiName" yaml:"msiName" mapstructure:"msiName"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// ServiceAccountName corresponds to the JSON schema field "serviceAccountName".
	ServiceAccountName string `json:"serviceAccountName" yaml:"serviceAccountName" mapstructure:"serviceAccountName"`

	// Geneva logs resources subscriptions
	Subscriptions []interface{} `json:"subscriptions" yaml:"subscriptions" mapstructure:"subscriptions"`
}

type MCE struct {
	// Bundle corresponds to the JSON schema field "bundle".
	Bundle ContainerImage `json:"bundle" yaml:"bundle" mapstructure:"bundle"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type MDSD struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type MDSDCert struct {
	// Logs certificate issuer
	Issuer string `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Logs certificate name
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Logs certificate type
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type MSICredentialsRefresher struct {
	// Certificate corresponds to the JSON schema field "certificate".
	Certificate MSICredentialsRefresherCertificate `json:"certificate" yaml:"certificate" mapstructure:"certificate"`

	// Early refresh interval before credential is eligible for refresh. For testing,
	// 0 means no early refresh. Example: 24h
	EarlyRefreshFrequency string `json:"earlyRefreshFrequency" yaml:"earlyRefreshFrequency" mapstructure:"earlyRefreshFrequency"`

	// The client ID of the first party application that will be used by the refresher
	FirstPartyAppClientId *string `json:"firstPartyAppClientId,omitempty" yaml:"firstPartyAppClientId,omitempty" mapstructure:"firstPartyAppClientId,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// ImageArtifact corresponds to the JSON schema field "imageArtifact".
	ImageArtifact ImageArtifact `json:"imageArtifact" yaml:"imageArtifact" mapstructure:"imageArtifact"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// The name of the MSI that will be used by the refresher
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`
}

type MSICredentialsRefresherCertificate struct {
	// CommonName corresponds to the JSON schema field "commonName".
	CommonName string `json:"commonName" yaml:"commonName" mapstructure:"commonName"`

	// Issuer corresponds to the JSON schema field "issuer".
	Issuer CertificateIssuer `json:"issuer" yaml:"issuer" mapstructure:"issuer"`

	// Manage corresponds to the JSON schema field "manage".
	Manage bool `json:"manage" yaml:"manage" mapstructure:"manage"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// SANDNSNames corresponds to the JSON schema field "sanDnsNames".
	SANDNSNames []string `json:"sanDnsNames" yaml:"sanDnsNames" mapstructure:"sanDnsNames"`
}

type MSIRP struct {
	// DataPlaneAudienceResource corresponds to the JSON schema field
	// "dataPlaneAudienceResource".
	DataPlaneAudienceResource string `json:"dataPlaneAudienceResource" yaml:"dataPlaneAudienceResource" mapstructure:"dataPlaneAudienceResource"`
}

type Maestro struct {
	// Agent corresponds to the JSON schema field "agent".
	Agent Agent `json:"agent" yaml:"agent" mapstructure:"agent"`

	// Optional SAN base domain for Maestro Eventgrid certificates. If missing,
	// defaults to maestro.${dns.regionalSubdomain}.${dns.svcParentZoneName}
	CertDomain *string `json:"certDomain,omitempty" yaml:"certDomain,omitempty" mapstructure:"certDomain,omitempty"`

	// CertIssuer corresponds to the JSON schema field "certIssuer".
	CertIssuer CertificateIssuer `json:"certIssuer" yaml:"certIssuer" mapstructure:"certIssuer"`

	// EventGrid corresponds to the JSON schema field "eventGrid".
	EventGrid EventGrid `json:"eventGrid" yaml:"eventGrid" mapstructure:"eventGrid"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// Postgres corresponds to the JSON schema field "postgres".
	Postgres Postgres `json:"postgres" yaml:"postgres" mapstructure:"postgres"`

	// RestrictIstioIngress corresponds to the JSON schema field
	// "restrictIstioIngress".
	RestrictIstioIngress bool `json:"restrictIstioIngress" yaml:"restrictIstioIngress" mapstructure:"restrictIstioIngress"`

	// Server corresponds to the JSON schema field "server".
	Server Server `json:"server" yaml:"server" mapstructure:"server"`
}

type Metrics struct {
	// Cluster corresponds to the JSON schema field "cluster".
	Cluster Cluster `json:"cluster" yaml:"cluster" mapstructure:"cluster"`

	// RP corresponds to the JSON schema field "rp".
	RP RP `json:"rp" yaml:"rp" mapstructure:"rp"`
}

type Mgmt struct {
	// AKS corresponds to the JSON schema field "aks".
	AKS AKSConfig `json:"aks" yaml:"aks" mapstructure:"aks"`

	// ApplyKubeletFixes corresponds to the JSON schema field "applyKubeletFixes".
	ApplyKubeletFixes bool `json:"applyKubeletFixes" yaml:"applyKubeletFixes" mapstructure:"applyKubeletFixes"`

	// HcpBackups corresponds to the JSON schema field "hcpBackups".
	HcpBackups *HcpBackups `json:"hcpBackups,omitempty" yaml:"hcpBackups,omitempty" mapstructure:"hcpBackups,omitempty"`

	// Jaeger corresponds to the JSON schema field "jaeger".
	Jaeger interface{} `json:"jaeger,omitempty" yaml:"jaeger,omitempty" mapstructure:"jaeger,omitempty"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Prometheus deployment configuration
	Prometheus Prometheus `json:"prometheus" yaml:"prometheus" mapstructure:"prometheus"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type MinTLSVersion string

const MinTLSVersionTLSV12 MinTLSVersion = "TLSV1.2"
const MinTLSVersionTLSV13 MinTLSVersion = "TLSV1.3"

type Mise struct {
	// ARM corresponds to the JSON schema field "arm".
	ARM ARM `json:"arm" yaml:"arm" mapstructure:"arm"`

	// Whether to deploy MISE. Be careful where to enable MISE as it can't be deployed
	// in non-MSFT tenants.
	Deploy bool `json:"deploy" yaml:"deploy" mapstructure:"deploy"`

	// GenevaActions corresponds to the JSON schema field "genevaActions".
	GenevaActions GenevaActions `json:"genevaActions" yaml:"genevaActions" mapstructure:"genevaActions"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// Tracing configuration for OTLP traces.
	Tracing Tracing `json:"tracing" yaml:"tracing" mapstructure:"tracing"`
}

type Monitoring struct {
	// GrafanaMajorVersion corresponds to the JSON schema field "grafanaMajorVersion".
	GrafanaMajorVersion *string `json:"grafanaMajorVersion,omitempty" yaml:"grafanaMajorVersion,omitempty" mapstructure:"grafanaMajorVersion,omitempty"`

	// GrafanaName corresponds to the JSON schema field "grafanaName".
	GrafanaName string `json:"grafanaName" yaml:"grafanaName" mapstructure:"grafanaName"`

	// A space-separated list of Service Principals IDs, Types and their desired
	// grafana roles The format is: <principalId>/<principalType>/<role>, e.g.
	// 12345678-1234-1234-1234-123456789012/Group/Admin
	GrafanaRoles string `json:"grafanaRoles" yaml:"grafanaRoles" mapstructure:"grafanaRoles"`

	// GrafanaZoneRedundantMode corresponds to the JSON schema field
	// "grafanaZoneRedundantMode".
	GrafanaZoneRedundantMode ZoneRedundantMode `json:"grafanaZoneRedundantMode" yaml:"grafanaZoneRedundantMode" mapstructure:"grafanaZoneRedundantMode"`

	// The workspace name should include 4-63 letters, digits or '-'. The '-'
	// shouldn't be the first or the last symbol. We limit the name to 44 characters
	// so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	HcpWorkspaceName string `json:"hcpWorkspaceName" yaml:"hcpWorkspaceName" mapstructure:"hcpWorkspaceName"`

	// Icm corresponds to the JSON schema field "icm".
	Icm *Icm `json:"icm,omitempty" yaml:"icm,omitempty" mapstructure:"icm,omitempty"`

	// The workspace name should include 4-63 letters, digits or '-'. The '-'
	// shouldn't be the first or the last symbol. We limit the name to 44 characters
	// so we have a future option to use NSP:
	// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
	SvcWorkspaceName string `json:"svcWorkspaceName" yaml:"svcWorkspaceName" mapstructure:"svcWorkspaceName"`
}

type NSP struct {
	// AccessMode corresponds to the JSON schema field "accessMode".
	AccessMode *AccessMode `json:"accessMode,omitempty" yaml:"accessMode,omitempty" mapstructure:"accessMode,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

// A valid RFC1123 DNS label. Must start and end with a lowercase letter or number,
// and can contain hyphens in between.
type NamespaceName string

type NetworkDataplane string

const NetworkDataplaneAzure NetworkDataplane = "azure"
const NetworkDataplaneCilium NetworkDataplane = "cilium"

type NetworkPolicy string

const NetworkPolicyAzure NetworkPolicy = "azure"
const NetworkPolicyCilium NetworkPolicy = "cilium"

type OCPVersions struct {
	// ChannelGroups corresponds to the JSON schema field "channelGroups".
	ChannelGroups ChannelGroups `json:"channelGroups" yaml:"channelGroups" mapstructure:"channelGroups"`

	// DefaultVersion corresponds to the JSON schema field "defaultVersion".
	DefaultVersion DefaultVersion `json:"defaultVersion" yaml:"defaultVersion" mapstructure:"defaultVersion"`
}

type OIDC struct {
	// Frontdoor corresponds to the JSON schema field "frontdoor".
	Frontdoor Frontdoor `json:"frontdoor" yaml:"frontdoor" mapstructure:"frontdoor"`

	// StorageAccount corresponds to the JSON schema field "storageAccount".
	StorageAccount interface{} `json:"storageAccount" yaml:"storageAccount" mapstructure:"storageAccount"`
}

type OcMirror struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`

	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`

	// JobNamePrefix corresponds to the JSON schema field "jobNamePrefix".
	JobNamePrefix *string `json:"jobNamePrefix,omitempty" yaml:"jobNamePrefix,omitempty" mapstructure:"jobNamePrefix,omitempty"`

	// OperatorVersionsToMirror corresponds to the JSON schema field
	// "operatorVersionsToMirror".
	OperatorVersionsToMirror Csv `json:"operatorVersionsToMirror" yaml:"operatorVersionsToMirror" mapstructure:"operatorVersionsToMirror"`

	// PullSecretName corresponds to the JSON schema field "pullSecretName".
	PullSecretName string `json:"pullSecretName" yaml:"pullSecretName" mapstructure:"pullSecretName"`
}

type OndemandSync struct {
	// PullSecretName corresponds to the JSON schema field "pullSecretName".
	PullSecretName string `json:"pullSecretName" yaml:"pullSecretName" mapstructure:"pullSecretName"`
}

type Operator struct {
	// Bundle corresponds to the JSON schema field "bundle".
	Bundle ContainerImage `json:"bundle" yaml:"bundle" mapstructure:"bundle"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type OperatorConfig struct {
	// RoleNames corresponds to the JSON schema field "roleNames".
	RoleNames string `json:"roleNames" yaml:"roleNames" mapstructure:"roleNames"`
}

type Pav2 struct {
	// CloudName corresponds to the JSON schema field "cloudName".
	CloudName string `json:"cloudName" yaml:"cloudName" mapstructure:"cloudName"`
}

type Pko struct {
	// ImageManager corresponds to the JSON schema field "imageManager".
	ImageManager ContainerImage `json:"imageManager" yaml:"imageManager" mapstructure:"imageManager"`

	// ImagePackage corresponds to the JSON schema field "imagePackage".
	ImagePackage ContainerImage `json:"imagePackage" yaml:"imagePackage" mapstructure:"imagePackage"`

	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// ManagedIdentityName corresponds to the JSON schema field "managedIdentityName".
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// RemotePhaseManager corresponds to the JSON schema field "remotePhaseManager".
	RemotePhaseManager ContainerImage `json:"remotePhaseManager" yaml:"remotePhaseManager" mapstructure:"remotePhaseManager"`
}

type Postgres struct {
	// Number of days to retain backups for the PostgreSQL server.
	BackupRetentionDays int64 `json:"backupRetentionDays" yaml:"backupRetentionDays" mapstructure:"backupRetentionDays"`

	// ContainerizedDb corresponds to the JSON schema field "containerizedDb".
	ContainerizedDb *ContainerizedDb `json:"containerizedDb,omitempty" yaml:"containerizedDb,omitempty" mapstructure:"containerizedDb,omitempty"`

	// DatabaseName corresponds to the JSON schema field "databaseName".
	DatabaseName string `json:"databaseName" yaml:"databaseName" mapstructure:"databaseName"`

	// Deploy corresponds to the JSON schema field "deploy".
	Deploy bool `json:"deploy" yaml:"deploy" mapstructure:"deploy"`

	// Enable geo-redundant backups for the PostgreSQL server.
	GeoRedundantBackup bool `json:"geoRedundantBackup" yaml:"geoRedundantBackup" mapstructure:"geoRedundantBackup"`

	// MinTLSVersion corresponds to the JSON schema field "minTLSVersion".
	MinTLSVersion MinTLSVersion `json:"minTLSVersion" yaml:"minTLSVersion" mapstructure:"minTLSVersion"`

	// Name corresponds to the JSON schema field "name".
	Name PostgresName `json:"name" yaml:"name" mapstructure:"name"`

	// Password corresponds to the JSON schema field "password".
	Password *string `json:"password,omitempty" yaml:"password,omitempty" mapstructure:"password,omitempty"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// ServerStorageSizeGB corresponds to the JSON schema field "serverStorageSizeGB".
	ServerStorageSizeGB int64 `json:"serverStorageSizeGB" yaml:"serverStorageSizeGB" mapstructure:"serverStorageSizeGB"`

	// ServerVersion corresponds to the JSON schema field "serverVersion".
	ServerVersion string `json:"serverVersion" yaml:"serverVersion" mapstructure:"serverVersion"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

// Server name must only contain lowercase letters, numbers, and hyphens. The
// server name must not start or end in a hyphen. Name must be between 3 be 63
// characters long but we limited to 44 characters so we have a future option to
// use NSP:
// https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts
type PostgresName string

type Prometheus struct {
	// KubeStateMetrics corresponds to the JSON schema field "kubeStateMetrics".
	KubeStateMetrics *KubeStateMetrics `json:"kubeStateMetrics,omitempty" yaml:"kubeStateMetrics,omitempty" mapstructure:"kubeStateMetrics,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// NamespaceNetworkPolicyGroup corresponds to the JSON schema field
	// "namespaceNetworkPolicyGroup".
	NamespaceNetworkPolicyGroup *string `json:"namespaceNetworkPolicyGroup,omitempty" yaml:"namespaceNetworkPolicyGroup,omitempty" mapstructure:"namespaceNetworkPolicyGroup,omitempty"`

	// PrometheusConfigReloader corresponds to the JSON schema field
	// "prometheusConfigReloader".
	PrometheusConfigReloader *PrometheusConfigReloader `json:"prometheusConfigReloader,omitempty" yaml:"prometheusConfigReloader,omitempty" mapstructure:"prometheusConfigReloader,omitempty"`

	// PrometheusOperator corresponds to the JSON schema field "prometheusOperator".
	PrometheusOperator interface{} `json:"prometheusOperator,omitempty" yaml:"prometheusOperator,omitempty" mapstructure:"prometheusOperator,omitempty"`

	// PrometheusSpec corresponds to the JSON schema field "prometheusSpec".
	PrometheusSpec *PrometheusSpec `json:"prometheusSpec,omitempty" yaml:"prometheusSpec,omitempty" mapstructure:"prometheusSpec,omitempty"`
}

type PrometheusConfigReloader struct {
	// Image corresponds to the JSON schema field "image".
	Image *ContainerImageSha `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`
}

type PrometheusSpec struct {
	// Image corresponds to the JSON schema field "image".
	Image *ContainerImageSha `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// Replicas corresponds to the JSON schema field "replicas".
	Replicas *float64 `json:"replicas,omitempty" yaml:"replicas,omitempty" mapstructure:"replicas,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *ContainerResources `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// Retention corresponds to the JSON schema field "retention".
	Retention *string `json:"retention,omitempty" yaml:"retention,omitempty" mapstructure:"retention,omitempty"`

	// RetentionSize corresponds to the JSON schema field "retentionSize".
	RetentionSize *string `json:"retentionSize,omitempty" yaml:"retentionSize,omitempty" mapstructure:"retentionSize,omitempty"`

	// Shards corresponds to the JSON schema field "shards".
	Shards *float64 `json:"shards,omitempty" yaml:"shards,omitempty" mapstructure:"shards,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version *string `json:"version,omitempty" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type Prow struct {
	// The name of the KeyVault secret in the global AKV that stores the token used to
	// authenticate with Prow.
	GlobalKeyVaultTokenSecret *string `json:"globalKeyVaultTokenSecret,omitempty" yaml:"globalKeyVaultTokenSecret,omitempty" mapstructure:"globalKeyVaultTokenSecret,omitempty"`
}

type RP struct {
	// Account corresponds to the JSON schema field "account".
	Account string `json:"account" yaml:"account" mapstructure:"account"`
}

type RegionTest struct {
	// GatePromotion corresponds to the JSON schema field "gatePromotion".
	GatePromotion bool `json:"gatePromotion" yaml:"gatePromotion" mapstructure:"gatePromotion"`

	// ProwJobName corresponds to the JSON schema field "prowJobName".
	ProwJobName string `json:"prowJobName" yaml:"prowJobName" mapstructure:"prowJobName"`
}

type ReleaseApprover struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type ResourceGroupName string

type Resources struct {
	// Cpu corresponds to the JSON schema field "cpu".
	Cpu *string `json:"cpu,omitempty" yaml:"cpu,omitempty" mapstructure:"cpu,omitempty"`

	// Memory corresponds to the JSON schema field "memory".
	Memory *string `json:"memory,omitempty" yaml:"memory,omitempty" mapstructure:"memory,omitempty"`
}

type RoleSetName string

const RoleSetNameDev RoleSetName = "dev"
const RoleSetNameFf RoleSetName = "ff"
const RoleSetNamePublic RoleSetName = "public"

// Spec to control the desired behavior of rolling update.
type RollingUpdate struct {
	// The maximum number of pods that can be scheduled above the desired number of
	// pods. Value can be an absolute number (ex: 5) or a percentage of desired pods
	// (ex: 10%). This can not be 0 if MaxUnavailable is 0. Absolute number is
	// calculated from percentage by rounding up. Defaults to 25%. Example: when this
	// is set to 30%, the new ReplicaSet can be scaled up immediately when the rolling
	// update starts, such that the total number of old and new pods do not exceed
	// 130% of desired pods. Once old pods have been killed, new ReplicaSet can be
	// scaled up further, ensuring that total number of pods running at any time
	// during the update is at most 130% of desired pods.
	MaxSurge interface{} `json:"maxSurge,omitempty" yaml:"maxSurge,omitempty" mapstructure:"maxSurge,omitempty"`

	// The maximum number of pods that can be unavailable during the update. Value can
	// be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%).
	// Absolute number is calculated from percentage by rounding down. This can not be
	// 0 if MaxSurge is 0. Defaults to 25%. Example: when this is set to 30%, the old
	// ReplicaSet can be scaled down to 70% of desired pods immediately when the
	// rolling update starts. Once new pods are ready, old ReplicaSet can be scaled
	// down further, followed by scaling up the new ReplicaSet, ensuring that the
	// total number of pods available at all times during the update is at least 70%
	// of desired pods.
	MaxUnavailable interface{} `json:"maxUnavailable,omitempty" yaml:"maxUnavailable,omitempty" mapstructure:"maxUnavailable,omitempty"`
}

type RouteMonitorOperator struct {
	// BlackboxExporterImage corresponds to the JSON schema field
	// "blackboxExporterImage".
	BlackboxExporterImage ContainerImage `json:"blackboxExporterImage" yaml:"blackboxExporterImage" mapstructure:"blackboxExporterImage"`

	// OperatorImage corresponds to the JSON schema field "operatorImage".
	OperatorImage ContainerImage `json:"operatorImage" yaml:"operatorImage" mapstructure:"operatorImage"`
}

type SecretSyncController struct {
	// Image corresponds to the JSON schema field "image".
	Image ContainerImage `json:"image" yaml:"image" mapstructure:"image"`
}

type SemVer string

type Server struct {
	// K8S corresponds to the JSON schema field "k8s".
	K8S K8SDeployment `json:"k8s" yaml:"k8s" mapstructure:"k8s"`

	// Loglevel corresponds to the JSON schema field "loglevel".
	Loglevel int64 `json:"loglevel" yaml:"loglevel" mapstructure:"loglevel"`

	// ManagedIdentityName corresponds to the JSON schema field "managedIdentityName".
	ManagedIdentityName string `json:"managedIdentityName" yaml:"managedIdentityName" mapstructure:"managedIdentityName"`

	// MqttClientName corresponds to the JSON schema field "mqttClientName".
	MqttClientName string `json:"mqttClientName" yaml:"mqttClientName" mapstructure:"mqttClientName"`

	// Tracing corresponds to the JSON schema field "tracing".
	Tracing *Tracing `json:"tracing,omitempty" yaml:"tracing,omitempty" mapstructure:"tracing,omitempty"`
}

// A valid RFC1123 DNS subdomain. Multiple RFC1123 DNS label devided by a dot.
type ServiceAccountName string

type ServiceKeyVault struct {
	// AssignNSP corresponds to the JSON schema field "assignNSP".
	AssignNSP *bool `json:"assignNSP,omitempty" yaml:"assignNSP,omitempty" mapstructure:"assignNSP,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name KeyVaultName `json:"name" yaml:"name" mapstructure:"name"`

	// Private corresponds to the JSON schema field "private".
	Private bool `json:"private" yaml:"private" mapstructure:"private"`

	// Region corresponds to the JSON schema field "region".
	Region string `json:"region" yaml:"region" mapstructure:"region"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// SoftDelete corresponds to the JSON schema field "softDelete".
	SoftDelete bool `json:"softDelete" yaml:"softDelete" mapstructure:"softDelete"`

	// TagKey corresponds to the JSON schema field "tagKey".
	TagKey string `json:"tagKey" yaml:"tagKey" mapstructure:"tagKey"`

	// TagValue corresponds to the JSON schema field "tagValue".
	TagValue string `json:"tagValue" yaml:"tagValue" mapstructure:"tagValue"`
}

type SharedIngressIPTag string

const SharedIngressIPTagBlank SharedIngressIPTag = ""
const SharedIngressIPTagFirstPartyUsageAROHcpProdInboundCustomerapi SharedIngressIPTag = "FirstPartyUsage=/aro-hcp-prod-inbound-customerapi"
const SharedIngressIPTagFirstPartyUsageNonProd SharedIngressIPTag = "FirstPartyUsage=/NonProd"

type Sku string

const SkuPremiumAzureFrontDoor Sku = "Premium_AzureFrontDoor"
const SkuStandardAzureFrontDoor Sku = "Standard_AzureFrontDoor"

type Stable struct {
	// MaxVersion corresponds to the JSON schema field "maxVersion".
	MaxVersion interface{} `json:"maxVersion" yaml:"maxVersion" mapstructure:"maxVersion"`

	// MinVersion corresponds to the JSON schema field "minVersion".
	MinVersion SemVer `json:"minVersion" yaml:"minVersion" mapstructure:"minVersion"`
}

type StorageAccount struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The location of the storage account private link. Not every region supports
	// private links so we need to be able to override the default location.
	PrivateLinkLocation *string `json:"privateLinkLocation,omitempty" yaml:"privateLinkLocation,omitempty" mapstructure:"privateLinkLocation,omitempty"`

	// Whether the storage account is public or private. If private, it can only be
	// accessed via Azure Front Door
	Public bool `json:"public" yaml:"public" mapstructure:"public"`

	// ZoneRedundantMode corresponds to the JSON schema field "zoneRedundantMode".
	ZoneRedundantMode ZoneRedundantMode `json:"zoneRedundantMode" yaml:"zoneRedundantMode" mapstructure:"zoneRedundantMode"`
}

type SubscriptionMetadata struct {
	// AirsRegisteredUserPrincipalId corresponds to the JSON schema field
	// "airsRegisteredUserPrincipalId".
	AirsRegisteredUserPrincipalId *string `json:"airsRegisteredUserPrincipalId,omitempty" yaml:"airsRegisteredUserPrincipalId,omitempty" mapstructure:"airsRegisteredUserPrincipalId,omitempty"`

	// CertificateDomains corresponds to the JSON schema field "certificateDomains".
	CertificateDomains []string `json:"certificateDomains,omitempty" yaml:"certificateDomains,omitempty" mapstructure:"certificateDomains,omitempty"`

	// DisplayName corresponds to the JSON schema field "displayName".
	DisplayName string `json:"displayName" yaml:"displayName" mapstructure:"displayName"`

	// FeatureFlags corresponds to the JSON schema field "featureFlags".
	FeatureFlags []string `json:"featureFlags,omitempty" yaml:"featureFlags,omitempty" mapstructure:"featureFlags,omitempty"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`

	// Providers corresponds to the JSON schema field "providers".
	Providers map[string]interface{} `json:"providers,omitempty" yaml:"providers,omitempty" mapstructure:"providers,omitempty"`

	// UsePlannedQuota corresponds to the JSON schema field "usePlannedQuota".
	UsePlannedQuota *bool `json:"usePlannedQuota,omitempty" yaml:"usePlannedQuota,omitempty" mapstructure:"usePlannedQuota,omitempty"`
}

type Svc struct {
	// AKS corresponds to the JSON schema field "aks".
	AKS AKSConfig `json:"aks" yaml:"aks" mapstructure:"aks"`

	// Istio corresponds to the JSON schema field "istio".
	Istio Istio `json:"istio" yaml:"istio" mapstructure:"istio"`

	// Jaeger corresponds to the JSON schema field "jaeger".
	Jaeger interface{} `json:"jaeger,omitempty" yaml:"jaeger,omitempty" mapstructure:"jaeger,omitempty"`

	// NSP corresponds to the JSON schema field "nsp".
	NSP *NSP `json:"nsp,omitempty" yaml:"nsp,omitempty" mapstructure:"nsp,omitempty"`

	// Prometheus deployment configuration
	Prometheus *Prometheus `json:"prometheus,omitempty" yaml:"prometheus,omitempty" mapstructure:"prometheus,omitempty"`

	// RG corresponds to the JSON schema field "rg".
	RG ResourceGroupName `json:"rg" yaml:"rg" mapstructure:"rg"`

	// Subscription corresponds to the JSON schema field "subscription".
	Subscription SubscriptionMetadata `json:"subscription" yaml:"subscription" mapstructure:"subscription"`
}

type Tracing struct {
	// Defines exporter address
	Address string `json:"address" yaml:"address" mapstructure:"address"`

	// Defines which exporter the SDK should use
	Exporter string `json:"exporter" yaml:"exporter" mapstructure:"exporter"`
}

type UntaggedImagesRetention struct {
	// Number of days to retain untagged images
	Days uint16 `json:"days" yaml:"days" mapstructure:"days"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled" yaml:"enabled" mapstructure:"enabled"`
}

type ZoneRedundantMode string

const ZoneRedundantModeAuto ZoneRedundantMode = "Auto"
const ZoneRedundantModeDisabled ZoneRedundantMode = "Disabled"
const ZoneRedundantModeEnabled ZoneRedundantMode = "Enabled"

// Zones to use for the pools.
type Zones interface{}

type Zones_1 interface{}
