// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package arohcpapi

type ConfigMetaSchemaJSON struct {
	// The schema version of the configuration file
	Schema *string `json:"$schema,omitempty" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// A map of clouds and their configuration
	Clouds map[string]interface{} `json:"clouds,omitempty" yaml:"clouds,omitempty" mapstructure:"clouds,omitempty"`

	// Defaults corresponds to the JSON schema field "defaults".
	Defaults map[string]interface{} `json:"defaults,omitempty" yaml:"defaults,omitempty" mapstructure:"defaults,omitempty"`
}
